// any query beyond these domain entities is the limitaiton

export let DOMAIN_ENTITIES = [
    "allergy",
    "alternative",
    "analgesic",
    "anthistamine",
    "antihistamine",
    "antimotility",
    "antitussive",
    "antiviral",
    "bacteria",
    "bismuth",
    "blood",
    "boil",
    "caffiene",
    "chest",
    "chills",
    "clog",
    "cold",
    "condition",
    "cook",
    "cough",
    "cramp",
    "danger",
    "decongestant",
    "diarrhea",
    "diarrhea_foods_not_allowed_contains_fructose",
    "diarrhea_foods_not_allowed_contains_lactose",
    "diarrhea_foods_not_allowed_irritate_stomach",
    "diarrhea_foods_not_allowed_produces_gas",
    "doctor",
    "dose",
    "drug",
    "effect",
    "expectorant",
    "eye",
    "face",
    "facemask",
    "fatigue",
    "fever",
    "fiber",
    "forum",
    "function",
    "germs",
    "grains",
    "guide",
    "gulay",
    "hand",
    "hands",
    "head",
    "headache",
    "immune",
    "infect",
    "inflammation",
    "influenza",
    "influenza_foods_allowed",
    "influenza_foods_not_allowed",
    "influenza_foods_not_allowed_caffeinated",
    "influenza_foods_not_allowed_caffeinated_drinks",
    "influenza_foods_not_allowed_greasy_foods",
    "influenza_foods_not_allowed_hard_grains",
    "influenza_foods_not_allowed_sugary_foods",
    "lozenge",
    "lung",
    "mask",
    "meat",
    "mucus",
    "nausea",
    "nose",
    "nsaid",
    "parasite",
    "peel",
    "raw",
    "sneeze",
    "solution",
    "sore",
    "stiff",
    "stomach",
    "stool",
    "strain",
    "stress",
    "sweet",
    "throat",
    "unpeeled",
    "unwashed",
    "vaccine",
    "virus",
    "vomit",
    "wash",
    "water",
    "zinc",
    // "antibiotic",
    // "antidiarrheal",
    // "artificial",
    // "brand",
    // "buy",
    // "consult",
    // "drink",
    // "eat",
    // "eat",
    // "generic",
    // "patient",
    // "problem",
    // "reason",
    // "rest",
    // "salt",
    // "wear"
    // "acute",
    // "acute",
    // "asthma",
    // "avoid",
    // "boil",
    // "capsule",
    // "care",
    // "chew",
    // "chronic",
    // "clean",
    // "clean",
    // "clear",
    // "clear",
    // "clog",
    // "close",
    // "combat",
    // "comfort",
    // "compare",
    // "consult",
    // "consume",
    // "contaminated",
    // "contract",
    // "deficiency",
    // "discuss",
    // "disinfect",
    // "disrupt",
    // "dissolve",
    // "features",
    // "hamak",
    // "harm",
    // "hydrate",
    // "identify",
    // "irritate",
    // "malnutrition",
    // "obtain",
    // "oily",
    // "reduce",
    // "remove",
    // "sprays",
    // "start",
    // "stop",
    // "swallow",
    // "upset",
    // "wear",
    // additional words
    // from generic
]

export let PRIORITY_VERBS = [
    ""
]

DOMAIN_ENTITIES.push([
    
])
