import { encodeSubstitution } from "@/api/config/model";

export const substitutionsGeneric = [
    encodeSubstitution('about',['tungkol']),
    encodeSubstitution('according',['according(.*)','ayon','tig']),
    encodeSubstitution('act',['act(.*)']),
    encodeSubstitution('acute',['(.*)tindi(.*)', '(.*)seryoso(.*)', '(k|c)ritical']),
    encodeSubstitution('address',['address(.*)','(.*)tugon(.*)']),
    encodeSubstitution('advantage',['advantag(.*)']),
    encodeSubstitution('ako',['ak(i|o)ng']),
    encodeSubstitution('allergy',['allerg(.*)']),
    encodeSubstitution('allow',['allow(.*)']),
    encodeSubstitution('alternative',['(.*)(p|m|n)alit']),
    encodeSubstitution('alternative',['(.*)s(a|ina)mbi(.*)']),
    encodeSubstitution('alternative',['alternati(.*)', 'substitut(.*)', '(.*)pilian(.*)']),
    encodeSubstitution('alternative',['else','(an)?others?','(be|a)sides?','maliban']),
    encodeSubstitution('alternative',['herb(.*)']),
    encodeSubstitution('analgesic',['analgesics', 'paracetamol', 'biogesic', 'aspirin', 'acetaminophen','painkillers?']),
    encodeSubstitution('antibiotic',['antibiotics']),
    encodeSubstitution('antidiarrheal',['antidiarrheals']),
    encodeSubstitution('antihistamine',['antihistamines', 'benadryl', 'cetirizine','histamines?']),
    encodeSubstitution('antimotility',['(anti)?motilit(.*)', 'loperamide', 'imodium']),
    encodeSubstitution('antitussive',['antitussives', 'dextromenthorpan', 'robitussin', 'dextromenthorpan']),
    encodeSubstitution('antiviral',['antivirals']),
    encodeSubstitution('any',['any(.*)']),
    encodeSubstitution('ask',['(.*)(e|i)dsan?']),
    encodeSubstitution('ask',['(.*)inquir(.*)', '(.*)question(.*)','(.*)t(in|um)?an(o|u)ng(.*)']),
    encodeSubstitution('ask',['ask(.*)','(.*)hing(i|an)']),
    encodeSubstitution('ask',['ku?westi?y(u|o)n(in)?']),
    encodeSubstitution('avoid',['(.*)avoid(.*)', '(.*)evad(.*)', '(.*)prevent(.*)']),
    encodeSubstitution('avoid',['(.*)iwasan(.*)','(.*)agapan','(.*)ibsan(.*)']),
    encodeSubstitution('avoid',['(.*)lay(u|o)(.*)', '(.*)ilag(.*)']),
    encodeSubstitution('avoid',['(.*)restrict(.*)', '(.*)b(in|um)awal(.*)']),
    encodeSubstitution('avoid',['(t(e|i|u|o)m|(n|p)(e|i)dt|(n|m|p)akat|t(e|i)n(i|e)m|t)angka']),
    encodeSubstitution('bacteria',['ba(k|c)ter(.*)','salmonella']),
    encodeSubstitution('bad',['(.*)sama(.*)', 'masama(ng)?', 'poor', 'wors(.*)']),
    encodeSubstitution('bad',['exacerbat(.*)', 'severe','(.*)lunsan(.*)','(.*)aggravat(.*)','(.*)(p|m)alala(.*)']),
    encodeSubstitution('bad',['negativ(.*)']),
    encodeSubstitution('bad',['unsuit(.*)','unsafe','undesirable','adverse']),
    encodeSubstitution('balance',['(.*)balan(s|c)(.*)',]),
    encodeSubstitution('basic',['basics']),
    encodeSubstitution('become',['maging','pagiging']),
    encodeSubstitution('benefit',['(.*)benefi(.*)','(.*)ben(i|e)pisi?y(.*)']),
    encodeSubstitution('between',['pagitan','gitna']),
    encodeSubstitution('bismuth',['subsalicylates?']),
    encodeSubstitution('blood',['(.*)dugo']),
    encodeSubstitution('blood',['blood(.*)','(.*)(l|d|pa)ug(u|o)']),
    encodeSubstitution('body',['katawan','lawas']),
    encodeSubstitution('boil',['(.*)(t|m)abel(.*)']),
    encodeSubstitution('boil',['(.*)boil(.*)', '(.*)kul(o|u(in|han)g?)']),
    encodeSubstitution('bottle',['bottles?','bote(ng)?','but(u|o)l']),
    encodeSubstitution('brand',['brand(.*)','tatak']),
    encodeSubstitution('bring',['bring(.*)', 'brought']),
    encodeSubstitution('buy',['(m|n|p|(g|n|b|m|k)ap|pin)amasan?', '(.*)pamasa(.*)','pamasen']),
    encodeSubstitution('buy',['bought', '(.*)b(um|in)?ili']),
    encodeSubstitution('buy',['order(.*)', '(.*)purchas(.*)']),
    encodeSubstitution('caffiene',['(.*)caffien(.*)']),
    encodeSubstitution('care',['(.*)prote(c|k)t(.*)']),
    encodeSubstitution('care',['car(e|i)(.*)', '(.*)ingat(.*)','alaga(ng|an)?','(.*)ngalaga(.*)']),
    encodeSubstitution('carry',['carri(.*)','kaakibat','(.*)dala']),
    encodeSubstitution('center',['(.*)centers']),
    encodeSubstitution('chance',['chances?','tsansa','(.*)?kataon']),
    encodeSubstitution('change',['chang(.*)','(.*)babago']),
    encodeSubstitution('chest',['dibdib','lad(i|e)b']),
    encodeSubstitution('chronic',['(.*)t(in|um)?agal(.*)', '(.*)prolong(.*)']),
    encodeSubstitution('chronic',['(n|m)a(o|u|w)get']),
    encodeSubstitution('clean',['((b|n|m|p|k)a(n?g)?)?(o|u)w?gas(i|an)?', '((k|m|n|p)a)?n?gagas(i|an)?', 'g(u|e)magas', '(.*)gagas(.*)']),
    encodeSubstitution('clean',['(.*)clean(.*)', '(.*)sanitiz(.*)', '(.*)disinfect(.*)', '(.*)wash(.*)','hygiene']),
    encodeSubstitution('clean',['(.*)limp(i|y)(o|u)(.*)', '(.*)l(um)?inis(.*)', '(.*)h(um|in)?ugas(.*)']),
    encodeSubstitution('clear',['(.*)clear(.*)']),
    encodeSubstitution('clog',['(.*)b(in|um)?ara(do(ng)?)?']),
    encodeSubstitution('clog',['(.*)clog(.*)']),
    // encodeSubstitution('clog',['stuff(.*)','(.*)congest(.*)']),
    encodeSubstitution('close',['clos(.*)']),
    encodeSubstitution('cold',['colds', 'sepu', 'sipon', '(i|e)?ngog(en)?']),
    encodeSubstitution('comfort',['(.*)comfort(.*)','(.*)k(u|o)mportable(.*)']),
    encodeSubstitution('compare',['compar(.*)']),
    encodeSubstitution('compose',['(.*)compos(.*)', 'parts?']),
    encodeSubstitution('condition',['(k|c)(u|o)ndi(si?yon|tions?)', 'kalagayan']),
    encodeSubstitution('consider',['consider(.*)','(.*)konsidera']),
    encodeSubstitution('consult',['(.*)ilayn?']),
    encodeSubstitution('consult',['(.*)k(u|o)ns(o|u)lta']),
    encodeSubstitution('consult',['(.*)tingin']),
    encodeSubstitution('consult',['check(ups?)?']),
    encodeSubstitution('consult',['consult(.*)', '(.*)(k(u|o)|m(o|u))?ns(o|u)lta(h(a|i)n|si?yon)?']),
    encodeSubstitution('contain',['(.*)contain(.*)']),
    encodeSubstitution('contribute',['(.*)contribut(.*)']),
    encodeSubstitution('cook',['(i|pi|ki)?(n|m|g)a(lu|w)t(o|u)n?','(pina|ma|na|pa|ba)n?g?il(o|u)t(o|u)(n|an|wan)?','(.*)l(o|u)t(o|u)(.*)','(m|g|n)al(o|u)t(o|u)']),
    encodeSubstitution('cook',['(pina|napa|naka)?((m|n|p)ag?)?(pa|ka|i)?l(in|um)?u(lu)?t(o|ong|uing?|uang?)?']),
    encodeSubstitution('cook',['cook(.*)']),
    encodeSubstitution('correct',['correct(.*)', '(.*)(d|r)apat','(.*)tama(.*)', 'wasto(.*)', 'right']),
    encodeSubstitution('correct',['proper(.*)']),
    encodeSubstitution('cost',['(.*)pila', '(.*)p(u|o)l(u|o)', '(.*)presy(.*)', 'pric(.*)', 'promo', 'diskwento']),
    encodeSubstitution('cost',['b(in|um)?aya(d|r)(.*)','expens(.*)']),
    encodeSubstitution('cost',['cost(.*)', '(.*)gast(o|u)(.*)', '(.*)mahal', '(.*)kano','rate']),
    encodeSubstitution('cost',['money', 'pera(.*)', 'budget']),
    encodeSubstitution('cough',['cough(.*)', '(.*)bat(u|o)k', '(um|in|(m|n|p)ag)?u?ubo(ng)?','u?ubuh(i|a)n']),
    encodeSubstitution('counter',['(.*)counter(.*)']),
    encodeSubstitution('cramp',['(.*)cramp(.*)']),
    encodeSubstitution('danger',['(.*)banta']),
    encodeSubstitution('danger',['(.*)challeng(.*)']),
    encodeSubstitution('danger',['(.*)danger(.*)', '(.*)pinsala', 'delikado(.*)']),
    encodeSubstitution('danger',['(.*)h(um|in)?amak(.*)']),
    encodeSubstitution('danger',['(.*)nganib']),
    encodeSubstitution('danger',['(.*)threat(.*)']),
    encodeSubstitution('danger',['harm(.*)']),
    encodeSubstitution('danger',['(.*)h(um)?amak(.*)']),
    encodeSubstitution('danger',['susceptible', 'suspect', 'vulnerable', 'distress', 'hazards?', 'risk(.*)']),
    encodeSubstitution('day',['days','araw']),
    encodeSubstitution('deal',['deal(.*)']),
    encodeSubstitution('decongestant',['decongestants?', 'sudafed', 'pseudoephedrine']),
    encodeSubstitution('depend',['depend(.*)']),
    encodeSubstitution('describe',['(.*)explain(.*)']),
    encodeSubstitution('describe',['defin(.*)', '((p|n|m)ag?)(paki)?(pa|papa)?li(li)?wanag(an|in)?', 'determine', 'ipaklaro', 'kahulugan', 'recogniz(.*)']),
    encodeSubstitution('describe',['descri(be|bes|bed|ption|ptions)', '(paki|i)?explain(s|ed|ing|ations?)', 'ilarawan', '(ma|na)?ipa(pa)?liwanag','(.*)liwanag', 'overview(s)']),
    encodeSubstitution('develop',['(.*)develop(.*)']),
    encodeSubstitution('diagnose',['diagnos(.*)']),
    encodeSubstitution('diarrhea',['(.*)diarrhea(.*)','(.*)tae?tae','(.*)tag(u|o)d(o|u)']),
    encodeSubstitution('diarrhea',['(.*)lbm','bowel']),
    encodeSubstitution('diet',['(.*)diet(.*)']),
    encodeSubstitution('differ',['(.*)b(e|i)(b(e|i))?da(ia|ya|yan)']),
    encodeSubstitution('differ',['(in|um|ka|pinagka|pagka|(n|m)apag|(n|m|p)ag)?(ka)?(ka|i)?iba(hin|han|ng)?']),
    encodeSubstitution('differ',['differen(.*)', 'contrast(.*)?','disparit(.*)']),
    encodeSubstitution('differ',['dissimilar(.*)']),
    encodeSubstitution('digest',['(.*)digest(.*)','(.*)tunaw(.*)']),
    encodeSubstitution('discuss',['discuss(.*)']),
    encodeSubstitution('distance',['distanc(.*)']),
    encodeSubstitution('distinguish',['distinguish(.*)']),
    encodeSubstitution('doctor',['(.*)d(u|o)(c|k)t(u|o)(l|r)s?','professionals?']),
    encodeSubstitution('doctor',['espesyalist(.*)', 'physicians?', 'experts?','practitioners?']),
    encodeSubstitution('doctor',['n(u|a)rs(.*)', '(c|k)lini(c|k)(.*)', '(.*)ospital(.*)', 'specialists?','klinika']),
    encodeSubstitution('dose',['(.*)dos(es|ing|is|ages?)']),
    encodeSubstitution('downsides',['drawbacks']),
    encodeSubstitution('drink',['(.*)(e|i)n(o|u)m(.*)']),
    encodeSubstitution('drink',['drink(.*)','beverages?']),
    encodeSubstitution('drink',['panulak']),
    encodeSubstitution('drug',['gam(o|u)t','therap(.*)', 'medicines?','remed(yo?|ies)' ]),
    encodeSubstitution('drug',['(.*)drugs', 'medisin(.*)', 'kinina', 'gam(u|o)t', 'supplement(.*)','vitamins?','bitamina']),
    encodeSubstitution('drugstore',['b(u|o)tika','(.*)dagang(.*)','merkado','market','grocery']),
    encodeSubstitution('drugstore',['drugstores', 'tinda(.*)', 'stores?', 'pharmac(.*)', 'parmasya','retail','shops?']),
    encodeSubstitution('easy',['eas(.*)', '((n|m)aka(ka)?|pinaka|i)?((n|m|p)ag?)?(pa(pa|ng?)|i|ka)?d(um)?a(da)?li(ng)?']),
    encodeSubstitution('eat',['(.*)kain(.*)']),
    encodeSubstitution('eat',['(.*)pegk(e|a)n(.*)', 'k(i|e)(ne)?man', '(.*)kanen', 'kananan', 'kakan','gakanan','ipakan',"(.*)sepa"]),
    encodeSubstitution('eat',['consum(.*)']),
    encodeSubstitution('eat',['eat(.*)', 'ate']),
    encodeSubstitution('eat',['food(.*)']),
    encodeSubstitution('eat',['fruits?', 'prutas','(o|u)nga']),
    encodeSubstitution('eat',['tsibuging?', 'baong?']),
    encodeSubstitution('effect',['(.*)(a|e)ffect(.*)', '(.*)(a|e)pekt(.*)', '(.*)labasan']),
    encodeSubstitution('effect',['impact(.*)']),
    encodeSubstitution('effect',['(.*)bisa(.*)']),
    encodeSubstitution('effect',['(.*)d(um|in)?ulot(.*)']),
    encodeSubstitution('effect',['(.*)l(um)?abas(.*)']),
    encodeSubstitution('effect',['(.*)react(.*)', '(.*)reaksi?yon(.*)']),
    encodeSubstitution('effect',['(.*)result(.*)', 'conseq(.*)']),
    encodeSubstitution('effect',['l(e|i)?(nem|m)?y(u|o)']),
    encodeSubstitution('elder',['elder(.*)','mata(ta)?nda(ng)?', 'matuwa']),
    encodeSubstitution('electrolyte',['electrolyt(.*)']),
    encodeSubstitution('enough',['adequate', 'sapat']),
    encodeSubstitution('ensure',['certain', '(.*)sigur(.*)']),
    encodeSubstitution('every',['bawat']),
    encodeSubstitution('example',['examples', 'halimbawa','instances?']),
    encodeSubstitution('exist',['exist(.*)']),
    encodeSubstitution('expectorant',['expectorants', 'guaifenesin']),
    encodeSubstitution('eye',['eyes', 'mata']),
    encodeSubstitution('face',['buntal', 'mukha']),
    encodeSubstitution('facility',['facilities']),
    encodeSubstitution('fatigue',[ '(.*)p(in)?agod(.*)', '(.*)hapo', '(.*)pagur(a|i)n']),
    encodeSubstitution('fatigue',['(.*)exert(.*)', 'exhaust(.*)']),
    encodeSubstitution('fatigue',['fatig(.*)','(.*)lugat(.*)','(.*)tegel']),
    encodeSubstitution('feel',['((n|m)ag?|(n|m)aka(ka)?|paki(ki)?)?(r|d)(um)?a((r|d)a)?mdam(an)?']),
    encodeSubstitution('feel',['(.*)(d|r)anas(.*)']),
    encodeSubstitution('feel',['(.*)feel(.*)', 'felt', 'experienc(.*)']),
    encodeSubstitution('feel',['(.*)gedam(.*)']),
    encodeSubstitution('fever',[ '(.*)s(um|in)?inat(.*)' ]),
    encodeSubstitution('fever',['(.*)(m|n|k)ayaw(.*)', '(b|m|n|p)(i|e)gkaya(w|o|u)']),
    encodeSubstitution('fever',['(.*)chill(.*)', '(.*)nginig']),
    encodeSubstitution('fever',['(.*)egkel']),
    encodeSubstitution('fever',['(.*)l(um)?agnat(.*)']),
    encodeSubstitution('fever',['fevers']),
    encodeSubstitution('find',['(.*)h(um|in)?anap(.*)']),
    encodeSubstitution('find',['find(.*)', '(.*)hanap(.*)','found']),
    encodeSubstitution('find',['seek(.*)']),
    encodeSubstitution('forum',['ahensya']),
    encodeSubstitution('forum',['forums','web(.*)','artikulo',"online","balita", "news","hotline"]),
    encodeSubstitution('frequent',[ '(.*)d(um|in)?alas(.*)']),
    encodeSubstitution('frequent',['frequency', 'always','daily','beses','(pa)?lagi(ng)?']),
    encodeSubstitution('frequent',['often', 'regular','(.*)dtandang','common']),
    encodeSubstitution('function',['purpos(.*)','function(.*)']),
    encodeSubstitution('generic',['generics', '((pin|nap)aka)?(pang)?karaniwang?']),
    encodeSubstitution('get',['(.*)acquir(.*)']),
    encodeSubstitution('get',['(.*)catch(.*)','caught']),
    encodeSubstitution('get',['(.*)contract(.*)']),
    encodeSubstitution('get',['(.*)k(um)?uha(.*)','(.*)kun(a|i)n']),
    encodeSubstitution('get',['(.*)kuha','((g|m|n|p|b)a)?(ka)?k(u|o|w)a', 'kem(w|u)a']),
    encodeSubstitution('get',['(.*)obtain(.*)']),
    encodeSubstitution('get',['(.*)receiv(.*)','induc(.*)']),
    encodeSubstitution('get',['(g|n|m|k)aalatan']),
    encodeSubstitution('get',['g(o|e)t(.*)']),
    encodeSubstitution('give',['((nap|pin)aka|pi)?((n|m|p)ag?)?(pa|papa|ka|kaka|i)?b(um)?i(bi)?ga?y(a|ang?)?']),
    encodeSubstitution('give',['(.*)b(um|in)?igay(.*)','((m|n)aka(ka)?)?((n|m|p)ag?|i)?i?b(um|in)?i(bi)?ga?y(ang?)?']),
    encodeSubstitution('give',['(.*)bigay','mami(mi)?gay']),
    encodeSubstitution('give',['(m(e|i)n(i|e))?((n|m|p)(e|a))?(ka)?(i|e)ngg?ay']),
    encodeSubstitution('give',['g(ive(n|s)?|ave)','pakangguna']),
    encodeSubstitution('go',['(.*)angay(.*)']),
    encodeSubstitution('go',['(.*)p(um)?unta(.*)']),
    encodeSubstitution('go',['(.*)pawang(.*)', 'l(i|e)?mu','be?l(u|o)']),
    encodeSubstitution('go',['go(ing)?','went','visit(.*)','steer(.*)']),
    encodeSubstitution('good',['(.*)ganda(.*)']),
    encodeSubstitution('good',['best', 'mapi?ya','mapia']),
    encodeSubstitution('group',['groups', 'grupo', '((n|m|p)ag?)?k(um)?u(ku)?mp(u|o)l(ang?)?', '(.*)pangkat(.*)']),
    encodeSubstitution('guide',['(.*)g(um)?abay(.*)','follow(.*)','(.*)un(o|u)t(an)?']),
    encodeSubstitution('guide',['(.*)sundin','(.*)sunod','(.*)sundan']),
    encodeSubstitution('guide',['(.*)guid(.*)']),
    encodeSubstitution('guide',['(.*)direct(.*)', '(.*)direksi?yong?']),
    encodeSubstitution('guide',['panuto', '(.*)utos', '(.*)bilin', '(.*)hakbang', '(.*)tuntunin']),
    
    encodeSubstitution('hand',['hands', 'l(e|i)ma', '(.)kamay', 'daliri']),
    encodeSubstitution('handa',['(.*)h(um)?anda(.*)']),
    encodeSubstitution('happen',['happen(.*)','(m|n|k)anggula','(m|n|p)angya(ya)?ri(.*)']),
    encodeSubstitution('happen',['occur(.*)', 'panahon','period','arise']),
    encodeSubstitution('have',['having','equip(.*)']),
    encodeSubstitution('head',['(o|u)lo']),
    encodeSubstitution('headache',['(.*)lang(o|u)t(.*)']),
    encodeSubstitution('headache',['dizz(.*)','(.*)hilo']),
    encodeSubstitution('health',['health(.*)','(.*)lusog(.*)']),
    encodeSubstitution('help',['(.*)kadtag']),
    encodeSubstitution('help',['(.*)t(um|in)?ul(u|o)ng(.*)']),
    encodeSubstitution('help',['(.*)tabang(.*)', 'tinemabang']),
    encodeSubstitution('help',['aid(.*)']),
    encodeSubstitution('help',['help(.*)', 'assist(.*)']),
    encodeSubstitution('high',['high(.*)','(.*)taas(.*)']),
    encodeSubstitution('how',['(.*)paa?no(.*)?', 'pan(u|o)n?']),
    encodeSubstitution('hydrate',['(.*)hydrat(.*)']),
    encodeSubstitution('ilan',['i?ilang']),
    encodeSubstitution('immune',['resistance','resisten(.*)']),
    encodeSubstitution('important',['(.*)importan(.*)', '((m|k)a)?halaga(.*)', '(nec)?ess(it(ies|y)|ary|ential(y|s)?)', 'need(.*)', 'significan(.*)']),
    encodeSubstitution('important',['(.*)kailangan(.*)','nasisita','requir(.*)']),
    encodeSubstitution('important',['crucial']),
    encodeSubstitution('include',['(.*)includ(.*)','(.*)involv(.*)','compose(.*)','kabilang']),
    encodeSubstitution('include',['(.*)kasama(.*)']),
    encodeSubstitution('increase',['(.*)dagdag(.*)','addition(.*)']),
    encodeSubstitution('increase',['(pina|(m|n)apa|(m|n)aka)?((m|n|p)ag?)?(pa|ka|i)?d(in|um)?a(da)?gdag(ang?)?']),
    encodeSubstitution('infect',['(.*)h(um|in)?awa(.*)']),
    encodeSubstitution('infect',['(.*)infect(.*)', '(.*)impeks(.*)']),
    encodeSubstitution('infect',['(.*)k(in|um)?alat(.*)']),
    encodeSubstitution('infect',['(.*)p(in|um)?asa(.*)']),
    encodeSubstitution('infect',['(.*)spread(.*)','(.*)transmi(.*)']),
    encodeSubstitution('inflammation',['inflam(.*)', '(pama|na)?maga']),
    encodeSubstitution('influenza',['(.*)flu','(.*)influenza(.*)', '(.*)trangkaso(.*)']),
    encodeSubstitution('ingredient',['ingredients','sangkap','substances?']),
    encodeSubstitution('initial',['initiat(.*)']),
    encodeSubstitution('instruct',['(.*)instruct(.*)']),
    encodeSubstitution('interact',['(.*)interact(.*)','(.*)salamuha']),
    encodeSubstitution('irritate',['(.*)kati','(.*)ngati', 'pangangatog']),
    encodeSubstitution('irritate',['(.*)rita','(.*)gatel']),
    encodeSubstitution('kaya',['(.*)k(in|um)?aya(.*)']),
    encodeSubstitution('kaysa',['kesa']),
    encodeSubstitution('kill',['(.*)killer(.*)','(.*)p(um|in)?atay(.*)']),
    encodeSubstitution('kind',['(.*)balangan', 'uri']),
    encodeSubstitution('kind',['anyo(.*)','antas']),
    encodeSubstitution('kind',['class(.*)', 'klas(.*)']),
    encodeSubstitution('kind',['form(.*)', '(.*)porma', 'types?']),
    encodeSubstitution('kind',['kinds?']),
    encodeSubstitution('kind',['varia(.*)']),
    encodeSubstitution('lagay',['(.*)lagay(.*)']),
    encodeSubstitution('laki',['((nap|pin)aka)?(ma)?l(um)?a(la)?ki(ng)?']),
    encodeSubstitution('lason',['(pina|(m|n)apa|(m|n)aka|maki)?((m|n|p)ag?)?(pa|ka|i|ini)?l(in|um)?a(la)?song?']),
    encodeSubstitution('lead',['leads']),
    encodeSubstitution('level',['levels']),
    encodeSubstitution('link',['link(.*)','connect(.*)','koneksi?yon']),
    encodeSubstitution('list',['(.*)l(um)?ista(.*)', 'enumerat(.*)','rundown']),
    encodeSubstitution('locate',['(.*)locat(.*)','places?','lugar']),
    encodeSubstitution('lozenge',['lozenges']),
    encodeSubstitution('lung',['lungs','baga','respir(.*)']),
    encodeSubstitution('make',['ma(de|k(es|ing))']),
    encodeSubstitution('malnutrition',['malnutrisi?yon','(.*)malnourish(.*)',]),
    encodeSubstitution('manage',['manag(.*)', '(.*)tili(.*)']),
    encodeSubstitution('many',['(.*)(r|d)ami','((k|m)a)?dakel']),
    encodeSubstitution('mask',['(.*)mask(.*)']),
    encodeSubstitution('mayroon',['mayroong', 'meron', '(m|n|p)agka(ka)?roon']),
    encodeSubstitution('mean',['mean(.*)']),
    encodeSubstitution('measure',['(.*)measur(.*)']),
    encodeSubstitution('meat',['chick(.*)', 'beef(.*)', 'pork(.*)', 'pig(.*)']),
    encodeSubstitution('meat',['fish(.*)', 'seda']),
    encodeSubstitution('meat',['manok', 'baka', 'baboy']),
    encodeSubstitution('meat',['meat(.*)', 'karn(.*)']),
    encodeSubstitution('method',['method(.*)', 'ways?', '(pamama|pa)raang?', 'ukit', 'approach(.*)','techniq(.*)','paraan']),
    encodeSubstitution('method',['pro(c|s)e(.*)']),
    encodeSubstitution('mistake',['mistake(.*)']),
    encodeSubstitution('mode',['modes']),
    encodeSubstitution('mouth',['bunganga', 'bibig', 'ngal(e|i)', 'oral(.*)']),
    encodeSubstitution('movement',['mov(.*)']),
    encodeSubstitution('mucus',['plema','pleghm']),
    encodeSubstitution('naging',['nagiging']),
    encodeSubstitution('name',['names', 'pangalan(.*)','(.*)ngalan?']),
    encodeSubstitution('natin',['nating']),
    encodeSubstitution('nausea',['(.*)nause(.*)', '(.*)d(um|in)?uwal']),
    encodeSubstitution('negative',['negati(.*)']),
    encodeSubstitution('neglect',[ '(.*)?tad(e|ay|ai)n?', '(.*)talipenda']),
    encodeSubstitution('neglect',['(.*)balewala(.*)']),
    encodeSubstitution('neglect',['(.*)hayaan']),
    encodeSubstitution('neglect',['(pin|(m|n)ap|bin|a)?((m|n|p)ag?)?(pa|papa|ka|kaka)?b(in)?a(ba)?ya(ang?)?']),
    encodeSubstitution('neglect',['neglect(.*)','(.*)bayaan','(.*)tadayn?','pabaya']),
    encodeSubstitution('nito',['nitong']),
    encodeSubstitution('none',['da']),
    encodeSubstitution('nose',['ilong', 'ng(e|i)long', 'nasal']),
    encodeSubstitution('not',['huwag', 'wag','ayaw']),
    encodeSubstitution('not',['hindi','di', 'kundi', '(d(e|i))?kena']),

    encodeSubstitution('nsaid',['nsaids', 'painkillers', 'ibuprofen', 'naproxen', 'advil', 'mortin', 'medicol', 'alaxan', '(non)?steroidal']),
    encodeSubstitution('nutrient',['(.*)sustans(.*)']),
    encodeSubstitution('nutrient',['nutri(.*)']),
    encodeSubstitution('option',['choices?','choose','chosen?']),
    encodeSubstitution('option',['options']),
    encodeSubstitution('organization',['organi(.*)']),
    encodeSubstitution('outbreak',['outbreaks']),
    encodeSubstitution('pain',['masakit', '((m|n)a)l(i|e)p(i|e)d(i|e)s(an)?']),
    encodeSubstitution('pandemic',['pandemya']),
    encodeSubstitution('parasite',['parasit(.*)','kagaw']),
    encodeSubstitution('patient',['patients', 'pasyente', 'pasinti']),
    encodeSubstitution('payag',['(.*)p(in|um)?ayag(.*)']),
    encodeSubstitution('peel',['(.*)b(in|um)?alat(.*)']),
    encodeSubstitution('peel',['peel(.*)', '((m|n|p)ag?)?b(um|in)?a(ba)?lat(ang?)?']),
    encodeSubstitution('person',['person(.*)']),
    encodeSubstitution('person',['ta(o|w)','individuals']),
    encodeSubstitution('point',['point(.*)','punto']),
    encodeSubstitution('popular',['sikat','kila','tanyag']),
    encodeSubstitution('possible',['posib(.*)']),
    encodeSubstitution('prefer',['(.*)preferr(.*)']),
    encodeSubstitution('prescribe',['prescri(.*)', 'reseta']),
    encodeSubstitution('present',['present(.*)']),
    encodeSubstitution('primary',['pangunahing']),
    encodeSubstitution('problem',['(.*)problema(.*)','(.*)binasa','(.*)sira','damag(.*)','impair(.*)']),
    encodeSubstitution('problem',['complicat(.*)', 'k(u|o)mplikasyon', 'concern(.*)', 'pr(u|o)bl(i|e)m(s|a|ang|ado(ng)?)?']),
    encodeSubstitution('problem',['downsides?','issues?']),
    encodeSubstitution('product',['produ(.*)']),
    encodeSubstitution('provide',['provide(.*)']),
    encodeSubstitution('can',['(m|n|k|g)apakay(an)?']),
    encodeSubstitution('can',['pu?wede(ng)?', 'kapakay', 'maaari(ng)?']),
    encodeSubstitution('qualified',['kalidad','approved','reliable','appropriate','suit(.*)']),
    encodeSubstitution('quick',['((k|m)a)?aga(d|pang?|rang?)']),
    encodeSubstitution('quick',['(.*)b(um|in)?ilis(.*)']),
    encodeSubstitution('quick',['(.*)samb(u|o)t(.*)']),
    encodeSubstitution('quick',['quick(.*)','fast(.*)','immediat(.*)']),
    encodeSubstitution('quick',['speed(.*)']),
    encodeSubstitution('raw',['(.*)hilaw(.*)']),
    encodeSubstitution('raw',['m(e|a(i|y))law', 'dama(lu|w)t(o|u)']),
    encodeSubstitution('raw',['uncook(.*)','undercook(.*)','pedt(u|o)dan']),
    encodeSubstitution('reason',['((n|m|g|k)ad|(b|p|n|m)(i|e)d)?sabap(an)?']),
    encodeSubstitution('reason',['caus(.*)', 'sanhi', 'factors?']),
    encodeSubstitution('reason',['nanggagaling']),
    encodeSubstitution('reason',['reasons?', 'rason','(.*)dahil(.*)', 'rationale?']),
    encodeSubstitution('reason',['trigger(.*)']),
    encodeSubstitution('recommend',['(.*)recommend(.*)', '(.*)rekomenda(.*)', '(.*)suggest(.*)']),
    encodeSubstitution('recommend',['(pina|(m|n)apa|(m|n)aka)?((m|n|p)ag?)?(pa|ka|i|ini)?r(in|um)?e(re)?k(u|o)menda(ng)?']),

    encodeSubstitution('regular',['regulate']),
    encodeSubstitution('relate',['relat(.*)']),
    encodeSubstitution('remove',['((b|m|p|n)aka?)?awa']),
    encodeSubstitution('remove',['((g|k|m|n)a)?awa']),
    encodeSubstitution('remove',['(.*)alis(.*)']),
    encodeSubstitution('remove',['(.*)awala']),
    encodeSubstitution('remove',['(.*)remov(.*)','eliminat(.*)']),
    encodeSubstitution('remove',['(bag)?awan?']),
    encodeSubstitution('remove',['(pa(ng|m))?((m|n)a|pina)?(pa)?(wa)?wala(ing?)?']),
    encodeSubstitution('remove',['(pa(ng|m))?((n|m|p)ag?)?(ka|kaka)?a?alis(ing?)?']),
    encodeSubstitution('remove',['(pa(ng|m))?((n|m|p)ag?)?(ka|kaka)?t(um|in)?a(ta)?nggal(ing?)?']),
    encodeSubstitution('remove',['(.*)baba']),
    encodeSubstitution('remove',['(.*)b(in|um)?awas(.*)']),
    encodeSubstitution('remove',['(.*)b(in|um)?aba(.*)']),
    
    // encodeSubstitution('remove',['(pina|(m|n)apa|(m|n)aka)?((m|n|p)ag?)?(pa|ka|i)?b(in|um)?a(ba)?ba(ng)?']),
    // encodeSubstitution('remove',['(pina|(m|n)apa|(m|n)aka)?((m|n|p)ag?)?(pa|ka|i)?b(in|um)?a(ba)?was(ang?)?']),
    encodeSubstitution('remove',['reduc(.*)','limit(.*)']),

    encodeSubstitution('replace',['(.*)replac(.*)']),
    encodeSubstitution('responsible',['(.*)respons(a|i)bl(.*)']),
    encodeSubstitution('rest',['((ka)?(n|p|m)(i|e)nd|d|d(e|i)m)(i|e)gka']),
    encodeSubstitution('rest',['((m|n|p|k)ag?)?(ka|kaka)?(si)?p(um|in)?a(pa)?hinga(hing?|ng?)?']),
    encodeSubstitution('rest',['(.*)(be?)?le?ne?k']),
    encodeSubstitution('rest',['(.*)degka']),
    encodeSubstitution('rest',['(.*)pahinga(.*)']),
    encodeSubstitution('rest',['rest(s|ed|ing)']),
    encodeSubstitution('restore',['restor(.*)', 'replenish(.*)']),
    encodeSubstitution('safe',['(.*)ligtas(.*)']),
    encodeSubstitution('safe',['safe(.*)', 'sav(e|es|ed|ing)', '(.*)l(um)?igtas(.*)']),
    encodeSubstitution('salt',['salt(.*)']),
    encodeSubstitution('same',['similar(.*)', 'tulad', 'like(.*)']),
    encodeSubstitution('sell',['sell(.*)','sold','(.*)benta(ng)?','(.*)tinda(ng)?']),
    encodeSubstitution('set',['sets']),
    encodeSubstitution('severe',['(.*)l(um)?ubha(.*)', 'adverse']),
    encodeSubstitution('severe',['sever(.*)', '(pina|napa|naka)?((m|n|p)ag?)?(pa|ka|i)?l(um)?a(la)?la(ng)?']),
    encodeSubstitution('should',['should(.*)']),
    encodeSubstitution('sick',[ 'ail(.*)','diseas(.*)', 'ill(.*)', 'karamdaman', 'pananakit','(.*)s(um|in)?akit(.*)']),
    encodeSubstitution('sick',['(.*)dsak(e|i)t', 'sick(.*)']),
    encodeSubstitution('sign',['(nad?|mad?|kad?|p?ed)?sipat(an)?', 'padsa', '(pala)?tanda(ang?)?', 'hudyat', 'bakas']),
    encodeSubstitution('sign',['sign(.*)', 'senya(s|les)', 'warn(.*)', 'cues?', 'babala']),
    encodeSubstitution('sila',['silang']),
    encodeSubstitution('sira',[ '(.*)s(um|in)?ira(.*)']),
    encodeSubstitution('situation',['situations', 'sitwasyon']),
    encodeSubstitution('skip',['skip(.*)']),
    encodeSubstitution('slow',['slow(.*)','(.*)b(um|in)?agal(.*)']),
    encodeSubstitution('sneeze',['((p|n)?(e|i)m)?bale?n']),
    encodeSubstitution('sneeze',['(.*)b(um|in)?ahing(.*)']),
    encodeSubstitution('sneeze',['sneez(.*)']),
    encodeSubstitution('solution',['solutions?', 'solusi?yon']),
    encodeSubstitution('source',['(.*)source(.*)','(.*)mula']),
    encodeSubstitution('special',['unique','special(.*)']),
    encodeSubstitution('standard',['(.*)standard(.*)','specific(.*)']),    
    encodeSubstitution('start',['init(.*)']),
    encodeSubstitution('stay',['stay(.*)','(.*)tili(ng)?']),
    encodeSubstitution('stiff',['stiff(.*)', 'kapa(pa)negas', 'paninigas', '(.*)tegas']),
    encodeSubstitution('stomach',['abdom(.*)','ti?yan', 'bituka','gut','gastro(.*)','(.*)intestin(.*)']),
    encodeSubstitution('stool',['stools?','feces','ta(e|i|y)']),
    encodeSubstitution('stop',['(.*)h(um|in)?into(.*)']),
    encodeSubstitution('stop',['(.*)inhibit(.*)']),
    encodeSubstitution('stop',['(.*)p(in|um)?igil(.*)']),
    encodeSubstitution('stop',['(.*)p(um|in)?igil(.*)']),
    encodeSubstitution('stop',['(.*)refrain(.*)']),
    encodeSubstitution('stop',['(.*)stop(.*)']),
    encodeSubstitution('stop',['(.*)suppress(.*)']),
    encodeSubstitution('stop',['(.*)t(in|um)?igil(.*)']),
    encodeSubstitution('strain',['(.*)strain(.*)']),
    encodeSubstitution('supplement',['(.*)supplement(.*)']),
    encodeSubstitution('support',['(.*)support(.*)']),
    encodeSubstitution('swallow',['(.*)l(um)?un(u|o)k(.*)', '(.*)len(o|u)k(.*)']),
    encodeSubstitution('swallow',['swallow(s|ed|ing)?']),
    encodeSubstitution('sweet',['(.*)sugar(.*)','desert(.*)']),
    encodeSubstitution('sweet',['(.*)sweet(.*)', 'syrup(.*)', 'cand(y|ies)','cakes?']),
    encodeSubstitution('sweet',['(.*)tamis', 'kendi', 'mamis(.*)']),
    encodeSubstitution('symptom',['symptoms', 'sintomas']),
    encodeSubstitution('tablet',['tablet(.*)']),
    encodeSubstitution('take',['((n|m)aka(ka)?|pina(ka)?|i)?((n|m|p)ag?)?(pa(pa|ng?)?|i|ka(ka)?)?t(um|in)?a(ta)?ke', 'tak(en|es|ing)', 'took']),
    encodeSubstitution('take',['intake']),
    encodeSubstitution('talk',['talk(.*)', '(.*)sabi(.*)']),
    encodeSubstitution('tayo',['tayong']),
    encodeSubstitution('tell',['(.*)labit(.*)']),
    encodeSubstitution('tell',['(.*)t(um|in)?ukoy(.*)']),
    encodeSubstitution('tell',['(.*)tukoy(.*)']),
    encodeSubstitution('tell',['advi(s|c)(.*)']),
    encodeSubstitution('tell',['appear(.*)', 'show(.*)','(.*)pakita(.*)']),
    encodeSubstitution('tell',['imporma(.*)']),
    encodeSubstitution('tell',['indicat(.*)', 'indika(.*)']),
    encodeSubstitution('tell',['inform(.*)','hint(.*)','overview','teach(.*)','(.*)turo']),
    encodeSubstitution('tell',['notic(.*)', '((m|n)a)?kikita(ng)?', 'nakita(ng)?']),
    encodeSubstitution('tell',['notic(.*)']),
    encodeSubstitution('tell',['p(i|e)dtal(u|o)n?']),
    encodeSubstitution('tell',['tell(.*)','told', 'recogni(.*)']),
    encodeSubstitution('term',['term(.*)']),
    encodeSubstitution('thing',['(.*)thing(.*)']),
    encodeSubstitution('throat',['throats', 'lalamunan']),
    encodeSubstitution('throat',['tid(i|e)k', 'bak(i|e)lngan']),
    encodeSubstitution('tip',['((m|n|p)ag?)?(pa|i)?p(in)?a(pa)?y(o|u)(h(a|i)n)?', 'paalala', 'isaalang(alang)?']),
    encodeSubstitution('tip',['remind(.*)', '(.*)cauti(.*)']),
    encodeSubstitution('tip',['tips']),
    encodeSubstitution('touch',['((m|p|n)ag|m?(e|i)n|)?(u|o)ba(in|yn?)']),
    encodeSubstitution('touch',['(.*)d(um|in)?ikit(.*)']),
    encodeSubstitution('touch',['(.*)h(in|um)?awak(.*)']),
    encodeSubstitution('touch',['(.*)l(um)?apit(.*)']),
    encodeSubstitution('touch',['(.*)s(um)?iksik(.*)']),
    encodeSubstitution('touch',['(bag|pag|min|m)amin?']),
    encodeSubstitution('touch',['contact(.*)', '((n|p|m)ag)?(o|u)bayn?', 'near(.*)','mobay']),
    encodeSubstitution('touch',['touch(.*)']),
    encodeSubstitution('treat',['(.*)b(um)?ut(i|hing?)']),
    encodeSubstitution('treat',['(.*)bagel','sooth(.*)']),
    encodeSubstitution('treat',['(.*)g(in|um)?am(o|u)t(.*)']),
    encodeSubstitution('treat',['(.*)g(um)?aling']),
    encodeSubstitution('treat',['(.*)g(um)?aling(.*)']),
    encodeSubstitution('treat',['(.*)kapi?yan?']),
    encodeSubstitution('treat',['(.*)l(um)?aban(.*)']),
    encodeSubstitution('treat',['(.*)l(um)?akas']),
    encodeSubstitution('treat',['(.*)l(um)?akas(.*)']),
    encodeSubstitution('treat',['(.*)l(um)?unas(.*)']),
    encodeSubstitution('treat',['(.*)rekober','(.*)recover(.*)']),
    encodeSubstitution('treat',['better','well','medicate','improv(.*)','kagkapya']),
    encodeSubstitution('treat',['combat(.*)','f(ou|i)ght(s|ing)?','(pang|k)ontra(hin)?']),
    encodeSubstitution('treat',['control(.*)']),
    encodeSubstitution('treat',['relie(.*)','alleviat(.*)']),
    encodeSubstitution('treat',['(.*)g(um)?inhawa(.*)']),
    encodeSubstitution('treat',['treat(.*)','cur(e|es|ed|ing)','heal(.*)', 'interv(.*)']),
    encodeSubstitution('try',['tr(ied|ying|ies)','(.*)s(um|in)?ub(o|u)k(.*)']),
    encodeSubstitution('turing',['itinuturing']),
    encodeSubstitution('typical',['typical(.*)']),
    encodeSubstitution('understand',['(.*)intindi(.*)']),
    encodeSubstitution('understand',['(.*)teka(w|o)', '(m|k|n|g)adtal(u|o)']),   
    encodeSubstitution('understand',['known?', '(m|n)?ala(la)?m(ang?)?',  'learn(.*)']),
    encodeSubstitution('understand',['underst(.*)','(m|k|g|n)ataw(an)?','aware(.*)','enlighten']),   
    encodeSubstitution('use',['(.*)g(um|in)?am(e|i)t(.*)']),
    encodeSubstitution('use',['(.*)gamit']),
    encodeSubstitution('use',['gemamit', '((n|m|g)a)?usal(.*)']),
    encodeSubstitution('use',['pamamagitan']),
    encodeSubstitution('use',['use(.*)', 'utili(.*)']),
    encodeSubstitution('vaccine',['(.*)bak(o|u)na(.*)']),
    encodeSubstitution('vaccine',['(.*)t(i|e)?b(i|e)?k',  ]),
    encodeSubstitution('vaccine',['(.*)vaccin(.*)']),
    encodeSubstitution('version',['version(.*)']),
    encodeSubstitution('virus',['viruses', 'viral']),
    encodeSubstitution('vomit',['((b|n|p|m)(an?g|aka))?(o|u)ta','(o|u)ta']),
    encodeSubstitution('vomit',['vomit(.*)', '(.*)s(um|in)?uka(.*)']),
    encodeSubstitution('wait',['wait(.*)','(b|p)?angatan','(.*)hintay(.*)']),
    encodeSubstitution('want',['want(.*)','(.*)gusto(.*)']),
    encodeSubstitution('watch',['see(.*)','look(.*)']),
    encodeSubstitution('water',['liquids?','likido', 'tubig', 'fluids?']),
    encodeSubstitution('weak',['(.*)h(um)ina(.*)']),
    encodeSubstitution('weak',['(.*)l(o|u)bay(an)?']),
    encodeSubstitution('weak',['weak(.*)', '(.*)hina']),
    encodeSubstitution('wear',['(.*)s(in|um)?uot(.*)']),
    encodeSubstitution('wear',['(.*)sukob']),
    encodeSubstitution('wear',['(.*)t(um)?a(ta)?ki?p(ang?)?', '(.*)t(in|um)akip(.*)','tinataki?pang?']),
    encodeSubstitution('wear',['(.*)tag(o|u)b(.*)']),
    encodeSubstitution('wear',['ta(w|o|u)b(i|e)', '(.*)tangg(o|u)b(.*)']),
    encodeSubstitution('wear',['wear(.*)','cover(.*)','wore']),
    encodeSubstitution('what',['(ano|ali)(ng)?', '(e|i)?ng(e|i)n']),
    encodeSubstitution('when',['k(e|ai)lan']),
    encodeSubstitution('when',['kanu']),
    encodeSubstitution('where',['(i|e)nda(u|o|w)']),
    encodeSubstitution('where',['(na)?saa?ng?']),
    encodeSubstitution('who',['who(m|se)', 'sino(ng)?', 'kanino(ng)?', 'ten', 'ta(i|y)n']),
    encodeSubstitution('why',['((e|i)n)?d(o|u)k(i|e)n']),
    encodeSubstitution('why',['(ba)?kit']),
    encodeSubstitution('work',['((n|m)ag?)?(g(um)?|p)a(ga)?na(ng)?', 'gana']),
    encodeSubstitution('work',['(.*)engg?(o|u)la(.*)']),
    encodeSubstitution('work',['(.*)g(um)?ana(.*)']), 
    encodeSubstitution('work',['(.*)g(um|in)?awa(.*)']),
    encodeSubstitution('work',['(.*)galbek(.*)']),
    encodeSubstitution('work',['(.*)galbek(.*)']),
    encodeSubstitution('work',['(.*)trabaho(.*)','(.*)pakilos']),     
    encodeSubstitution('work',['pak(i|e|ay)(r|d)an']),
    encodeSubstitution('work',['(.*)work(.*)', 'operat(.*)']),
    encodeSubstitution('work',['(.*)practic(.*)']),
    encodeSubstitution('work',['(.*)g(in|um)?awin?(.*)','paka(y|i)(d|r)an','(.*)pase?n']),
    encodeSubstitution('young',['child(.*)','wata','bata(ng)?','sanggol','infants?']),
]