import { encodeSubstitution } from "../engine/model";

export const terms = [
    
  encodeSubstitution(
    "not", [
      "cannot",
      "never",
      "do not",
      "don'?t",
      "can'?t",
      "won'?t"
    ]
  ),
  encodeSubstitution(
    "trigger", [
        "alter(ed|ing)?",
        "induce(d)?",
        "induc(ed|ing)",
        "cause(d|ing)?",
        "le(a)?d",
        "result(ed|ing)?",
        "giv(e|ing)",
        "gave",
        "mak(e|ing)",
        "made"
    ]
  ),
  encodeSubstitution(
    "drug",[
        "drugs",
        "medicine(s)?",
        "medication(s)?",
        "cure(d)?",
        "therap(y|ies)",
        "meds",
    ]
  ),
  encodeSubstitution(
    "parasite",[
        "parasit(es|ic)"
    ]
  ),
  encodeSubstitution(
    "get",[
        "contract",
        "experience"
    ]
  ),
  encodeSubstitution(
    "allergy",[
        "allerg(ic|ies)",
    ]
  ),
  encodeSubstitution(
    "take",[
        "drink",
        "eat"
    ]
  ),
  encodeSubstitution(
    "treat",[
        "relieve",
        "manage",
        "help",
        "important",
        "recommend",
        "fix",
        "tend",
        "mend",
        "address",
    ]
  ),
  encodeSubstitution(
    "consult",[
        "go",
        "see",
        "check"
    ]
  ),
  encodeSubstitution(
    "doctor",[
        "nurse",
        "hospital",
        "infirmary"
    ]
  ),
  encodeSubstitution(
    "buy",[
        "order",
        "purchase",
    ]
  ),
  encodeSubstitution(
    "avoid",[
        "prevent",
    ]
  ),
  encodeSubstitution(
    "food",[
        "snack",
        "meal",
    ]
  ),
  encodeSubstitution(
    "beverage",[
        "beverages"
    ]
  ),
  encodeSubstitution(
    "problem",[
        "trouble",
        "complication",
        "issue",
        "danger"
    ]
  ),
  encodeSubstitution(
    "use",[
        "administer",
        "apply"
    ]
  ),
  encodeSubstitution(
    "clean",[
        "sanitize",
        "wash"
    ]
  ),
]


export const engSubstitutions = 
    [].concat(terms)