import { encodeSubstitution } from "@/api/configuration/model";

export const substitutionsGeneric = [
    encodeSubstitution('act',['act(ions?|ivit(e|y|ies))', 'react(s|ed|ing|ions)?', 'reaksyon']),
    encodeSubstitution('acute',['matindi(ng)?', 'seryoso(ng)?', '(k|c)ritical']),
    encodeSubstitution('address',['addressing']),
    encodeSubstitution('advantage',['advantages']),
    encodeSubstitution('advice',['advis(e|able|ed)']),
    encodeSubstitution('agad',['((k|m)a)aga(d|pang?|rang?)']),
    encodeSubstitution('agad',['((n|m|k)a|(b|p)(i|e)d|(e|i))?samb(u|o)t(an|i)?']),
    encodeSubstitution('ako',['ak(ing|ong)']),
    encodeSubstitution('allergy',['allerg(ic|ies)']),
    encodeSubstitution('alternative',['alternati(b|bo|bong|ves)', 'substitut(es?|ions?)', '(na|ma)?(pag)?(pi|pini)?pilian(g)?']),
    encodeSubstitution('alternative',['(ka|nag|mag|naka|maka|i)?p(a|u)(pa|ma)?lit', 'pumalit']),
    encodeSubstitution('alternative',['(i?p(i|e)d|id?|ini|na|ma|ka|(m|n|p)akad)?s(a|ina)mbi(y?an)?']),
    encodeSubstitution('analgesic',['analgesics', 'paracetamol', 'biogesic', 'aspirin', 'acetaminophen']),
    encodeSubstitution('antibiotic',['antibiotics']),
    encodeSubstitution('antidiarrheal',['antidiarrheals']),
    encodeSubstitution('antihistamine',['antihistamines', 'benadryl', 'cetirizine']),
    encodeSubstitution('antimotility',['antimotilities', 'loperamide', 'imodium']),
    encodeSubstitution('antitussive',['antitussives', 'dextromethorphan', 'robitussin', 'dextromenthorpan']),
    encodeSubstitution('antiviral',['antivirals']),
    encodeSubstitution('avoid',['avoid(s|ed|ing)', 'eva(d(ed?|ing)|sion)?', 'prevent(s|ive|ing)?']),
    encodeSubstitution('avoid',['(um|(m|n|p)ag|(m|n)aka)?(i|ka)?iwas(ang?)?', '(m|n)aii?bsang?']),
    encodeSubstitution('avoid',['l(um)?a(la)?y(o|uang?)', '(um|in|(n|m|i?p)ag)i?ilag(ang?)?']),
    encodeSubstitution('avoid',['(t(e|i|u|o)m|(n|p)(e|i)dt|(n|m|p)akat|t(e|i)n(i|e)m|t)angka']),
    encodeSubstitution('bacteria',['bacter(ya|ial|ium)']),
    encodeSubstitution('bad',['(pina|pinaka|(m|n)apa|(m|n)aka)?((m|n|p)ag?)?(pa|ka|i|ini)?s(in|um)?a(sa)?ma(ng)?', 'masama(ng)?', 'poor', 'worse(n|ned|ning)']),
    encodeSubstitution('balance',['balan(se(ng)?|ced|ces)']),
    encodeSubstitution('balance',['(m|n|p)agba(ba)?lanse', 'balanc(e|es|ed|ing)']),
    encodeSubstitution('basic',['basics']),
    encodeSubstitution('benefit',['benefi(ts|cial)', 'ben(i|e)pisyo']),
    encodeSubstitution('bigay',['((m|n)aka(ka)?)?((n|m|p)ag?|i)?i?b(um|in)?i(bi)?ga?y(ang?)?']),
    encodeSubstitution('bigay',['mami(mi)?gay']),
    encodeSubstitution('bilis',['(pi|(m|n)a(pa)?)?((n|m)a|pa)?i?b(in|um)?i(bi)?lis((i|a)ng?)?']),
    encodeSubstitution('bisa',['((pina|napa)ka(ma)?|ma)?bisa(ng)?']),
    encodeSubstitution('blood',['(pina|(m|n)apa|(m|n)aka)?((m|n|p)ag?)?(pa|ka|i)?d(in|um)?u(du)?go(ng)?', '((p|m|b|n)(e|i)(g|d|b)?)?(pa)?(l|pa|)(u|o)g(u|o)']),
    encodeSubstitution('blood',['blood(s|y|iness)']),
    encodeSubstitution('body',['katawan']),
    encodeSubstitution('boil',['boil(s|ed|ing)', '((n|p|m)agpa|pina)?(pa)?(ku)?(mu)?kul(o|u(in|han)g?)']),
    encodeSubstitution('boil',['((m|n|p)(i|e)d|pakad|(i|e)d|(m|n)aka)?(ta)?tab(i|e)l(i|an)?', 't(e|i)n(i|e)mabel']),
    encodeSubstitution('brand',['brand(s|ed)']),
    encodeSubstitution('bring',['bring', 'brought']),
    encodeSubstitution('buy',['order(s|ed|ing)?', 'purchas(e|es|ed|ing)']),
    encodeSubstitution('buy',['bought', '(i|i?pi(na)?)?((m|n|p)ag?|i|(n|m)aka)?b(um)?i(bi)?l(i|i?h(i|a)ng?)']),
    encodeSubstitution('buy',['(m|n|p|(g|n|b|m|k)apa|pin)amasan?']),
    encodeSubstitution('care',['careful(ly)', 'caring']),
    encodeSubstitution('catch',['catch(es|ing)', 'caught']),
    encodeSubstitution('cause',['caus(es|ed|ing)', 'sanhi', 'factors?']),
    encodeSubstitution('cause',['trigger(s|ed|ing)']),
    encodeSubstitution('center',['centers']),
    encodeSubstitution('chill',['chill(s|ed|ing|y)', '(na|ma|pa)(ngi)?nginig']),
    encodeSubstitution('chill',['((p|n)(i|e)g)?kegkel', 'k(i|e)(n(e|i))?megkel', '(m|n|p)angegkel']),
    encodeSubstitution('choice',['choices']),
    encodeSubstitution('chronic',['malala(ng?)?', '(pang)?matagal(ang?)?', 'prolong(s|ed|ing)?']),
    encodeSubstitution('chronic',['(n|m)a(o|u|w)get']),
    encodeSubstitution('clean',['clean(s|ed|ing)', 'sanitiz(e|es|ed|ing|ation)', 'disinfect(ants?|ing|ion)?', 'wash(es|ed|ing)?']),
    encodeSubstitution('clean',['((n|m)aka(ka)?|pinaka|i)?((n|m|p)ag?)?(pa(pa|ng?)|i|ka)?h(um)?u(hu)?gas((a|i)ng?)?']),
    encodeSubstitution('clean',['((n|m)aka(ka)?|pinaka|i)?((n|m|p)ag?)?(pa(pa|ng?)|i|ka)?l(um)?i(li)?nis((a|i)ng?)?']),
    encodeSubstitution('clean',['((b|n|m|p|k)a(n?g)?)?(o|u)w?gas(i|an)?', '((k|m|n|p)a)?n?gagas(i|an)?', 'g(u|e)magas']),
    encodeSubstitution('clean',['(ka)?limp(i|y)(o|u)', 'kalinis']),
    encodeSubstitution('clear',['clear(s|ed|ing|ance|ances)']),
    encodeSubstitution('clog',['clog(s|ged|ging)']),
    encodeSubstitution('clog',['bara', '((n|m)aka(ka)?|(n|p|m)ag?)?b(um|in)?a(ba)?ra(do(ng)?)?']),
    encodeSubstitution('close',['close(d|s|ly)']),
    encodeSubstitution('cold',['colds', 'sepu', 'sipon', '(i|e)?ngog(en)?']),
    encodeSubstitution('combat',['combat(s|ed|ing)']),
    encodeSubstitution('common',['commonly', 'familiar']),
    encodeSubstitution('compare',['comparable']),
    encodeSubstitution('complication',['complicat(e|ed|es|ions?)', 'k(u|o)mplikasyon', 'concern(s|ed|ing)?`', 'pr(u|o)bl(i|e)m(s|a|ang|ado(ng)?)?']),
    encodeSubstitution('compose',['compos(es|ed|ition|ing)', 'parts?']),
    encodeSubstitution('condition',['(k|c)(u|o)ndi(syon|tions?)', 'kalagayan']),
    encodeSubstitution('consider',['consider(s|ed|ing|ations?)']),
    encodeSubstitution('consult',['consult(s|ed|ing|ations?)', '((m|n|p)?ag)?(pa)?k(u|o)(k(u|o)|mu)?ns(o|u)lta(h(a|i)n|si?yon)?']),
    encodeSubstitution('consult',['((m|n)aka)?((m|n|p)ag)?(pa|papa)?tingin']),
    encodeSubstitution('consult',['((na|ma)(ka)?)?(ke|pai|papai|kai)lay', '(ka|kapag)?angay(an)?']),
    encodeSubstitution('consult',['check(ups?)?']),
    encodeSubstitution('consume',['consum(ptions?|ing|ed|es|ing)']),
    encodeSubstitution('contact',['contact(s|ing|ed)', '(pag)?(o|u)bay', 'near(est)?']),
    encodeSubstitution('contact',['((n|m)aka(ka)?|pinaka|i)?((n|m|p)ag?)?(pa(pa|ng?)|i|ka)?l(um)?a(la)?pit((a|i)ng?)?']),
    encodeSubstitution('contact',['((n|m)aka(ka)?|pinaka|i)?((n|m|p)ag?)?(pa(pa|ng?)|i|ka)?d(um)?i(di)?kit((a|i)ng?)?']),
    encodeSubstitution('contact',['((n|m)aka(ka)?|pinaka|i)?((n|m|p)ag?)?(pa(pa|ng?)|i|ka)?s(um)?i(si)?ksik((a)ng?)?']),
    encodeSubstitution('contain',['contain(s|ed|ing)']),
    encodeSubstitution('contract',['contracting']),
    encodeSubstitution('contraindicated',['contraindications']),
    encodeSubstitution('contribute',['contribut(es|ed|ing)']),
    encodeSubstitution('cook',['cook(s|ed|ing)']),
    encodeSubstitution('cook',['(pina|napa|naka)?((m|n|p)ag?)?(pa|ka|i)?l(in|um)?u(lu)?t(o|ong|uing?|uang?)?']),
    encodeSubstitution('correct',['correct(s|ed|ing|ly|ions?)', '((m|n)a)?(ra|rara|da|da)pat', 'tama(ng)?', 'wasto(ng)?', 'right']),
    encodeSubstitution('correct',['proper(ly)?']),
    encodeSubstitution('cost',['costs', 'expens(e|es|ive(ly))?', '((n|m)aga)?gast(o|u)(s|sin|san)?', 'kamahal', '(mag)?kano']),
    encodeSubstitution('cost',['money', '(pinaka|napaka)?mura(ng)?', 'pera(ng)?', 'budget']),
    encodeSubstitution('cost',['(eng)?(gaga)?pila', 'kap(u|o)l(u|o)', 'presyo(ng)?', 'pric(e|ed|es|ing)', 'promo', 'diskwento']),
    encodeSubstitution('cough',['cough(s|ing)']),
    encodeSubstitution('counter',['counteract']),
    encodeSubstitution('cover',['cover(s|ed|ing)']),
    encodeSubstitution('cover',['((m|n)agsi)?((n|m|n|p)ag)?t(um)?a(ta)?ki?p(ang?)?', 'tinataki?pang?']),
    encodeSubstitution('cover',['(ed|nid|mid|ped|pid|pakad)tag(u|o)b(an)?', '(nad|mad|kad|ped)tag(o|u)b(an|i|e)?', 'ta(w|o|u)b(i|e)', 'tangg(o|u)b']),
    encodeSubstitution('cramp',['cramp(ed|ing|s)']),
    encodeSubstitution('danger',['danger(s|ous)', '(na|pa|ma)nganganib', 'pinsala', 'delikado(ng)?']),
    encodeSubstitution('danger',['susceptible', 'suspect', 'vulnerable', 'distress', 'hazards?', 'risk(y|s|ing)?']),
    encodeSubstitution('deal',['deal(s|ing)']),
    encodeSubstitution('decongestant',['decongestants?', 'sudafed', 'pseudoephedrine']),
    encodeSubstitution('depend',['depend(s|e|ing)']),
    encodeSubstitution('describe',['descri(be|bes|bed|ption|ptions)', '(paki|i)?explain(s|ed|ing|ations?)', 'ilarawan', '(ma|na)?ipa(pa)?liwanag', 'overview(s)']),
    encodeSubstitution('describe',['defin(e|es|ed|ing|ition)', '((p|n|m)ag?)(paki)?(pa|papa)?li(li)?wanag(an|in)?', 'determine', 'ipaklaro', 'kahulugan', 'recognize(s|ed)']),
    encodeSubstitution('develop',['develop(s|ed|ing|ment)']),
    encodeSubstitution('diagnose',['(diagno(s(e|i)s|sing|sed))']),
    encodeSubstitution('diarrhea',['diarrheal', '(n|p|m)ag(ta)?tae', '(m|p|n)agdu(du)?mi']),
    encodeSubstitution('diarrhea',['(b|g|n|m|p|k)(a|e|i)dtag(o|u)d(o|u)', '(((b|n|m|p)akad)|kinad)?tag(o|u)d(o|u)', '(b|g|n|m|p|k)(e|i)dtag(o|u)d(o|u)']),
    encodeSubstitution('diet',['dietary']),
    encodeSubstitution('differ',['differen(ces?|t|tiate)', 'contrasts?']),
    encodeSubstitution('differ',['(in|um|ka|pinagka|pagka|(n|m)apag|(n|m|p)ag)?(ka|i)?iba(hin|han|ng)?']),
    encodeSubstitution('differ',['(p?(i|e)m|((n|m|p)a)?kam|k(e|i)nam)?b(e|i)(b(e|i))?da(ia|ya|yan)']),
    encodeSubstitution('digest',['digest(ible|ion|ive)']),
    encodeSubstitution('direct',['directions?', 'direksyon']),
    encodeSubstitution('direct',['panuto', 'utos', 'bilin', 'hakbang', '(ali)?tuntunin']),
    encodeSubstitution('disease',['diseases', 'illness(es)?', 'karamdaman', 'pananakit']),
    encodeSubstitution('disease',['pedsak(e|i)t', '((n|m|p)ag(ka)?)?(ma|ka)?s(um)?a(sa)?k(e|i)t', 'sick(en|ness|ly)']),
    encodeSubstitution('distance',['distancing']),
    encodeSubstitution('distinguish',['distinguish(es|ing|ed)']),
    encodeSubstitution('doctor',['doctors', 'doktor', 'espesyalista(ng)?', 'physicians?', 'experts?']),
    encodeSubstitution('doctor',['n(u|a)rs(e|es)?', 'clinic(s|al)?', 'h?ospital?', 'specialists?']),
    encodeSubstitution('doctor',['penggamot', 'gemamot', 'd(o|u)kt(o|u)l', 'practitioners?']),
    encodeSubstitution('dose',['dos(es|ing|is|ages?)']),
    encodeSubstitution('downsides',['drawbacks']),
    encodeSubstitution('drink',['drink(s|ed|ing)']),
    encodeSubstitution('drug',['interventions?', 'therap(y|ies|eutics?)', 'medic(ines?|ations?|al)']),
    encodeSubstitution('drug',['drugs', 'medisina(ng)?', 'kinina', 'gam(u|o)t']),
    encodeSubstitution('drugstore',['drugstores', 'tindahan', 'stores?', 'pharmac(y|ies|euticals?)', 'parmasya']),
    encodeSubstitution('easy',['eas(e|ed|es|ily|ing)', '((n|m)aka(ka)?|pinaka|i)?((n|m|p)ag?)?(pa(pa|ng?)|i|ka)?d(um)?a(da)?li(ng)?']),
    encodeSubstitution('eat',['eat(s|en|ing)', 'ate']),
    encodeSubstitution('eat',['((n|m)aka(ka)?|pinaka|i)?((n|m|p)ag?)?(pa(pa|ng?)?|i|ka)?k(um)?a(ka)?in(in|g)?']),
    encodeSubstitution('eat',['pegkan', 'k(i|e)(ne)?man', 'kanen', 'kananan', 'gakanan', 'pegkanan']),
    encodeSubstitution('effect',['effect(s|ive|iveness|ivity|ively)', 'affect(s|ed|ing)', '((m|n)aka(ka)?)?(e|a)?(e|a)pekt(o(ng)?|ibo(ng)?)', 'bisa', 'kinalabasan', 'kalabasan']),
    encodeSubstitution('electrolyte',['electrolytes']),
    encodeSubstitution('eliminate',['eliminated']),
    encodeSubstitution('enough',['adequate', 'sapat']),
    encodeSubstitution('exacerbate',['exacerbated']),
    encodeSubstitution('example',['examples', 'halimbawa']),
    encodeSubstitution('exhaust',['exert(s|ed|ing|ion)', 'exhaust(s|ed|ing|ion)']),
    encodeSubstitution('exhaust',['((m|n)aka(ka)?)?((n|m|p)ag?)?p(in)?a(pa|papa)?god', '((m|n)aka(ka)?)?((n|m|p)ag?)?(pa|papa)?hapo', 'pagurin']),
    encodeSubstitution('exist',['exist(s|ed|ing)']),
    encodeSubstitution('expectorant',['expectorants', 'guaifenesin']),
    encodeSubstitution('experience',['expertise']),
    encodeSubstitution('eye',['eyes', 'mata']),
    encodeSubstitution('facility',['facilities']),
    encodeSubstitution('feel',['feel(s|ing)', 'felt', 'experienc(e|ed|es|ing)']),
    encodeSubstitution('feel',['((n|m)ag?|(n|m)aka(ka)?)?(r|d)(um)?a((r|d)a)?nas(ang?)?']),
    encodeSubstitution('feel',['((n|m)ag?|(n|m)aka(ka)?|paki(ki)?)?(r|d)(um)?a((r|d)a)?mdam(an)?']),
    encodeSubstitution('fever',['fevers']),
    encodeSubstitution('fever',['(ni|(n|m|p)ag?)?(la|ka|kaka)?l(um)?a(lag)?gnat(ing?)?', '((n|m|p)ag?)?(ka|kaka)?s(um)?i(si)?nat(ing?)?']),
    encodeSubstitution('fever',['(m|n|k)ayaw(an)?', '(b|m|n|p)(i|e)gkaya(w|o|u)']),
    encodeSubstitution('food',['foods', 'fruits?', 'prutas']),
    encodeSubstitution('food',['tsibuging?', 'baong?', 'pagkaing?']),
    encodeSubstitution('food',['((m|g|n)a|(pam(e|i)g)?p(i|e)g)?kan(i|e)n', '(o|u)nga']),
    encodeSubstitution('form',['form(s|ed|ation|ing)', 'porma', 'types?']),
    encodeSubstitution('form',['((i|e)m|(n|k)(in)?am)?balangan', 'uri']),
    encodeSubstitution('forms',['varian(ts?|ces?)', 'variations?', 'various']),
    encodeSubstitution('frequent',['frequency', 'always']),
    encodeSubstitution('frequent',['((n|m)aka(ka)?|pinaka|i)?((n|m|p)ag?)?(pa(pa|ng?)|i|ka)?d(um)?a(da)?las((a|i)ng?)?']),
    encodeSubstitution('galing',['((n|m)aka(ka)?|pinaka)?((n|m|p)ag?)?(pa|papa|i)?b(um)?u(bu)?t(i|hi(ng?))']),
    encodeSubstitution('galing',['((n|m)aka(ka)?|pinaka)?((n|m|p)ag?)?(pa|papa|i)?g(um)?a(ga)?ling(ang?)?']),
    encodeSubstitution('galing',['(n|m)aka(ka)?rekober']),
    encodeSubstitution('galing',['((n|m)aka(ka)?|pinaka)?((n|m|p)ag?)?(pa|papa|i|ka)?l(um)?a(la)?kas(ang?)?']),
    encodeSubstitution('galing',['((n|m|p|b)akag|(n|m|p)ag|(n|b|m|p)(i|e)g)?kapi?yan?', 'mapi?ya']),
    encodeSubstitution('generic',['generics', '((pin|nap)aka)?(pang)?karaniwang?']),
    encodeSubstitution('get',['(pi)?((n|m|p)ag?)?k(um|in)?u(ku)?(nan|ha(an|ang)?)', '(ku)?kun(an|in)', 'pagkakakuhanan', 'obtain(s|ed|ing)']),
    encodeSubstitution('get',['receiv(e|es|ed|ing)']),
    encodeSubstitution('get',['contract(s|ed|ing)']),
    encodeSubstitution('ginhawa',['((nap|pin)aka|pi)?((n|m|p)ag?)?(pa|papa|ka|kaka)?g(um)?i(gi)?nhaw(a|ang?)']),
    encodeSubstitution('ginhawa',['((nap|pin)aka|pi)?((n|m|p)ag?)?(pa|papa|ka|kaka)?g(um)?a(ga)?ang?']),
    encodeSubstitution('give',['((nap|pin)aka|pi)?((n|m|p)ag?)?(pa|papa|ka|kaka|i)?b(um)?i(bi)?ga?y(a|ang?)?']),
    encodeSubstitution('give',['g(ive(n|s)?|ave)']),
    encodeSubstitution('give',['(m(e|i)n(i|e))?((n|m|p)(e|a))?(ka)?(i|e)ngg?ay']),
    encodeSubstitution('good',['(pina|(m|n)apa|(m|n)aka)?((m|n|p)ag?)?(pa|ka|i)?g(in|um)?a(ga)?nda(ng)?']),
    encodeSubstitution('group',['groups', 'grupo', '((n|m|p)ag?)?k(um)?u(ku)?mp(u|o)l(ang?)?', 'pangkat']),
    encodeSubstitution('guide',['guid(es|ed|ding|ances?|elines?)']),
    encodeSubstitution('hamak',['(pina|(m|n)apa|(m|n)aka|maki)?((m|n|p)ag?)?(pa|ka|i|ini)?h(in|um)?a(ha)?mak(ing?)?']),
    encodeSubstitution('hanap',['(pina|(m|n)apa|(m|n)aka)?((m|n|p)ag?)?(pa|ka|i)?h(in|um)?a(ha)?nap(ang?)?']),
    encodeSubstitution('hand',['hands', 'l(e|i)ma', 'kamay', 'daliri']),
    encodeSubstitution('handa',['((n|m)aka(ka)?|pina(ka)?|i)?((n|m|p)ag?)?(pa(pa|ng?)?|i|ka)?h(um)?a(ha)?nda((a|i)ng?)?']),
    encodeSubstitution('harm',['harm(s|ful|ing|ed)']),
    encodeSubstitution('have',['having']),
    encodeSubstitution('hawak',['((nap|pin)aka|pi)?((n|m|p)ag?)?(pa|papa|ka|kaka)?h(um|in)?a(ha)?wak(ang?)?']),
    encodeSubstitution('hawak',['(bag|pag|min|m)amin?']),
    encodeSubstitution('head',['(o|u)lo']),
    encodeSubstitution('health',['healthy']),
    encodeSubstitution('help',['help(s|ful|ing|ed)']),
    encodeSubstitution('help',['((m|p|n)akad|(b|p)(i|e)d|(n|k|m)a)?(ta)?tabang(an|i)?', 'tinemabang']),
    encodeSubstitution('help',['((n|m)aka(ka)?|pinaka|i)?((n|m|p)ag?)?(pa(pa|ng?)|i|ka)?t(um)?u(tu)?l(ong|ungang?)']),
    encodeSubstitution('help',['(((n|m|p|b)(a|i|e)g?)|(n|m|p|b)akag)?(ka)?kadtag']),
    encodeSubstitution('high',['higher']),
    encodeSubstitution('hindi',['di', 'kundi', '(d(e|i))?kena']),
    encodeSubstitution('how',['(pa)?paa?no(ng)?', 'pan(u|o)n?']),
    encodeSubstitution('not',['huwag', 'wag']),
    encodeSubstitution('hydrate',['((m|n|p)ag?)?hydrat(e|es|ed|ion|ing)', 'magrehydrate']),
    encodeSubstitution('ilan',['ilang']),
    encodeSubstitution('important',['importan(ce|ces|te|teng)', '((m|k)a)?halaga(han|ng)?', '(nec)?ess(it(ies|y)|ary|ential(y|s)?)', 'need(s|ed|ing)', 'significan(t|ces?)']),
    encodeSubstitution('increase',['(pina|(m|n)apa|(m|n)aka)?((m|n|p)ag?)?(pa|ka|i)?d(in|um)?a(da)?gdag(ang?)?']),
    encodeSubstitution('indicate',['indicat(es|ed|ions?|ing|ors?)', 'indikasyon']),
    encodeSubstitution('induce',['induc(ed|es|ing|tion)']),
    encodeSubstitution('infect',['infect(s|ed|ions?|ing|ious)', '((n|m|p)ag?)?(ka(ka)?)?impeksyong?']),
    encodeSubstitution('inflammation',['inflammatory', '(pama)?maga']),
    encodeSubstitution('influenza',['((n|m|p)ag?)?(ka(ka)?)?influen(s|z)a(ng)?', '((n|m|p)ag?)?(ka(ka)?)?trangkaso(ng)?', '((n|m|p)ag?)?(ka(ka)?)?flu']),
    encodeSubstitution('inform',['inform(s|ed|er|ing|ations?)']),
    encodeSubstitution('ingat',['((n|m)aka(ka)?|pina(ka)?|i)?((n|m|p)ag?)?(pa(pa|ng?)?|i|ka)?(um)?ii?ngat(ang?)?']),
    encodeSubstitution('ingredient',['ingredients']),
    encodeSubstitution('initial',['initiates']),
    encodeSubstitution('inom',['((n|m)aka(ka)?|pina(ka)?|i)?((n|m|p)ag?)?(pa(pa|ng?)?|i|ka(ka)?)?(um|in)?ii?n(o|u)m(ang?|ing?)?', 'magpainom']),
    encodeSubstitution('inom',['panulak']),
    encodeSubstitution('inom',['((n|m|b|p)a(ka?|gi)?)?(pa(g|i)?|m?(in)?|(p|k|n)a?)?(e|i)n(o|u)m(an|en)?']),
    encodeSubstitution('inquire',['inquir(es|ed|ing|y)', 'question(s|ed|ing)?', '(n|p|m)agta(ta)?nong(an)?']),
    encodeSubstitution('inquire',['(pina|(m|n)apa|(m|n)aka)?((m|n|p)ag?)?(pa|ka|i)?t(in|um)?a(ta)?n(u|o)ng(ang?|ing?)?', '(n|m)apagta(ta)?nungan']),
    encodeSubstitution('inquire',['ku?westi?y(u|o)n(in)?']),
    encodeSubstitution('inquire',['(m|(m|n|p|b)an?g|(n|b|p|m)ang(e|i)ng)?(i|e)dsan?']),
    encodeSubstitution('instruct',['instruct(s|ed|ing|ions?)']),
    encodeSubstitution('interact',['interact(s|ed|ing|ions?)']),
    encodeSubstitution('involve',['involved']),
    encodeSubstitution('kailangan',['(ka|kina)?kailangan(g|ing)?']),
    encodeSubstitution('kapag',['pag']),
    encodeSubstitution('karami',['karaming']),
    encodeSubstitution('kasama',['kasamang']),
    encodeSubstitution('kati',['pangangati', 'pangangatog']),
    encodeSubstitution('kaya',['((n|m)a)?(ka)?k(in)?a(ka)?ya(hang?)?']),
    encodeSubstitution('kaysa',['kesa']),
    encodeSubstitution('kill',['killers?']),
    encodeSubstitution('kind',['kinds?', 'klasipikasyon']),
    encodeSubstitution('kind',['class(es|ifications?)?', 'klase(ng)?']),
    encodeSubstitution('know',['known', '(m|n)?ala(la)?m(ang?)?', 'kataw', 'learn(s|ed|ing)?']),
    encodeSubstitution('know',['((n|m|b|p)a)?(ka)?teka(w|o)', '(m|k|n|g)adtal(u|o)', '((n|m|g|p)ag?)?(pa)?kila(la)?(ng)?']),
    encodeSubstitution('kuha',['((g|m|n|p|b)a)?(ka)?k(u|o|w)a', 'kem(w|u)a']),
    encodeSubstitution('laban',['(pina|(m|n)apa|(m|n)aka|maki)?((m|n|p)ag?)?(pa|ka|i|ini)?l(in|um)?a(la)?ban(ang?)?']),
    encodeSubstitution('lagay',['(pina|napa)?((n|m)ag?|i)?l(um)?a(la)?ga?y(ang?)?']),
    encodeSubstitution('laki',['((nap|pin)aka)?(ma)?l(um)?a(la)?ki(ng)?']),
    encodeSubstitution('lason',['(pina|(m|n)apa|(m|n)aka|maki)?((m|n|p)ag?)?(pa|ka|i|ini)?l(in|um)?a(la)?song?']),
    encodeSubstitution('lead',['leads']),
    encodeSubstitution('level',['levels']),
    encodeSubstitution('link',['link(s|ages?|ed|ing)', 'connect(s|ed|ing|tions?)']),
    encodeSubstitution('list',['((n|m)aka(ka)?|pina(ka)?|i)?((m|n|p)ag?)?(i)?(pa)?l(um|in)?i(li)?sta(h(a|i)ng?)?', 'enumerat(e|es|ed|ing|ions?)']),
    encodeSubstitution('look',['look(s|ed|ing)']),
    encodeSubstitution('lozenge',['lozenges']),
    encodeSubstitution('lungs',['lung']),
    encodeSubstitution('lunok',['lumunok', 'lunukin']),
    encodeSubstitution('lusog',['kalusugan']),
    encodeSubstitution('make',['ma(de|k(es|ing))']),
    encodeSubstitution('malnutrition',['malnourishment']),
    encodeSubstitution('manage',['manag(ement|ing)', '((n|m)ag?pa|pa)?(pa|na)?tili(hing?)?']),
    encodeSubstitution('marami',['((m|n|p)ag?)(d|r)(um|in)?a(d|r)?mi(ng)?']),
    encodeSubstitution('mask',['masks']),
    encodeSubstitution('maximum',['maximiz(e|ing|es|ed)']),
    encodeSubstitution('mayroon',['mayroong', 'meron', '(m|n|p)agka(ka)?roon']),
    encodeSubstitution('mean',['mean(s|ing|t)']),
    encodeSubstitution('measure',['measures']),
    encodeSubstitution('meat',['meats', 'karne(ng)?']),
    encodeSubstitution('meat',['manok', 'baka', 'baboy']),
    encodeSubstitution('meat',['chicken', 'beef', 'pork', 'pig']),
    encodeSubstitution('mechanism',['mechanisms', 'mekanismo']),
    encodeSubstitution('method',['method(ical|s)', 'ways?', '(pamama|pa)raang?', 'ukit', 'approach(ed|ing|es)?']),
    encodeSubstitution('method',['procedures?', 'process(es|ed|ing)', 'proseso(ng)?']),
    encodeSubstitution('minimum',['manimiz(e|ing|es|ed)']),
    encodeSubstitution('mistake',['mistake(s|n)']),
    encodeSubstitution('mode',['modes']),
    encodeSubstitution('mouth',['bunganga', 'bibig', 'ngal(e|i)', 'oral(ly)?']),
    encodeSubstitution('movement',['movements']),
    encodeSubstitution('mula',['(pinag)?((n|m|p)ag?)?(si(si)?)?mu(mu)?la(ng?)?']),
    encodeSubstitution('naging',['nagiging']),
    encodeSubstitution('name',['names', 'pangalan(an)?']),
    encodeSubstitution('natin',['nating']),
    encodeSubstitution('nausea',['nauseous', '((p|n|m)ag?)?(ka|kaka)?d(um|in)?u(du)?wal']),
    encodeSubstitution('nausea',['((p|n|m)ag?)?(ka|kaka)?h(in)?i(hi)?lo(ng)?', '((p|n|m)ag?)?(ka|kaka)?s(in)?u(su)?lasok']),
    encodeSubstitution('nausea',['(pendada)?((g|n|m|k)a|ni|b)?lang(o|u)t(en)?', '(g|n|k)alang(o|u)t']),
    encodeSubstitution('negative',['negatively', 'negatibong']),
    encodeSubstitution('nito',['nitong']),
    encodeSubstitution('none',['da(la)?']),
    encodeSubstitution('nose',['ilong', 'ng(e|i)long', 'nasal']),
    encodeSubstitution('notice',['noticeable', '((m|n)a)?kikita(ng)?', 'nakita(ng)?']),
    encodeSubstitution('notice',['((m|n|p)ag?)?t(um|in)?u(tu)?koy(ing?)?', 'pagtukoy']),
    encodeSubstitution('nsaid',['nsaids', 'painkillers', 'ibuprofen', 'naproxen', 'advil', 'mortin', 'alaxan', 'medicol']),
    encodeSubstitution('nutrient',['nutrisyon', 'nutrit(ion|ious)']),
    encodeSubstitution('occur',['occur(s|ed|ring)', 'happen(s|ed|ings?)']),
    encodeSubstitution('option',['options']),
    encodeSubstitution('organization',['organizations', 'organisasyon']),
    encodeSubstitution('other',['others']),
    encodeSubstitution('outbreak',['outbreaks']),
    encodeSubstitution('pabaya',['(pin|(m|n)ap|bin|a)?((m|n|p)ag?)?(pa|papa|ka|kaka)?b(in)?a(ba)?ya(ang?)?']),
    encodeSubstitution('pabaya',['((m|n|p)ag?)?(pa|papa|ka|kaka|i)?b(um|in)?a(ba)?lewala(ing?)?']),
    encodeSubstitution('pabaya',['((n|m|p)a(p|k)ad|pinad|pap(i|e)d|pad|(i|e)d(taday)?|)?tad(e|ay|ai)n?', '((n|m|p|b)(i|e)d)?ta(ta)?lipenda']),
    encodeSubstitution('pain',['masakit', '((m|n)a)l(i|e)p(i|e)d(i|e)s(an)?']),
    encodeSubstitution('pandemic',['pandemya']),
    encodeSubstitution('parasite',['parasites', 'parasitic']),
    encodeSubstitution('parasite',['parasitiko', 'kagaw']),
    encodeSubstitution('patient',['patients', 'pasyente', 'pasinti']),
    encodeSubstitution('payag',['(pina)?((n|m|p)ag?)?p(um|in)?a(pa)?yag(ang?)?']),
    encodeSubstitution('peel',['peel(s|ed|ing)', '((m|n|p)ag?)?b(um|in)?a(ba)?lat(ang?)?']),
    encodeSubstitution('peel',['((b|p)ag|(p|m|b|n)ang|na|ma|ka)?(o|u)w?pis(i|an)?']),
    encodeSubstitution('person',['personal']),
    encodeSubstitution('place',['places']),
    encodeSubstitution('possible',['posib(leng|ilidad)?', 'possibilit(y|ies)']),
    encodeSubstitution('practice',['practic(es|ed|ing)']),
    encodeSubstitution('practice',['((n|m|p|k)ag?)?(pa|papa|ka|kaka)?g(um|in)?a(ga)?wa(ng?|in?)?']),
    encodeSubstitution('practice',['gawin?']),
    encodeSubstitution('practice',['(eng)?g(o|u)lan', 'pak(i|e|ay)(r|d)an']),
    encodeSubstitution('practice',['(ka|(n|m|p)(i|e))(ng)?galbek(an|en)?']),
    encodeSubstitution('prefer',['preferr(ed|ing|able)']),
    encodeSubstitution('prescribe',['prescribed', 'prescription']),
    encodeSubstitution('present',['presentations?']),
    encodeSubstitution('probiotic',['probiotics']),
    encodeSubstitution('product',['(produ(kto(ng)?)|cts)']),
    encodeSubstitution('professional',['professionals']),
    encodeSubstitution('provide',['provide(r|s|d|rs)']),
    encodeSubstitution('punta',['(pina|(m|n)apa|(m|n)aka)?((m|n|p)ag?)?(pa|ka|i)?p(in|um)?u(pu)?nta(ang?|hang?)?']),
    encodeSubstitution('punta',['((n|p|m)?(i|e)b)?pawang(an)?', '(bag|min|pag|m)?angay(an)?', 'l(i|e)?mu']),
    encodeSubstitution('pwede',['pu?wede(ng)?', 'kapakay', 'maaari(ng)?']),
    encodeSubstitution('pwede',['(m|n|k|g)apakay(an)?']),
    encodeSubstitution('qualified',['kalidad']),
    encodeSubstitution('raw',['hilaw']),
    encodeSubstitution('raw',['m(e|a(i|y))law', 'dama(lu|w)t(o|u)']),
    encodeSubstitution('reason',['reasons?', 'rason', '(ka)?dahil(an|anang)?', 'purpos(e|es|ed)']),
    encodeSubstitution('recommend',['recommend(s|ed|ations?|ing)']),
    encodeSubstitution('recommend',['(pina|(m|n)apa|(m|n)aka)?((m|n|p)ag?)?(pa|ka|i|ini)?r(in|um)?e(re)?k(u|o)menda(ng)?']),
    encodeSubstitution('recommend',['recommend(s|ed|ing|ations?)', 'rekomenda(do|syong?)', 'suggest(ed|ing|ions)?']),
    encodeSubstitution('reduce',['reduc(es|ed|ting|tions?)']),
    encodeSubstitution('reduce',['(pina|(m|n)apa|(m|n)aka)?((m|n|p)ag?)?(pa|ka|i)?b(in|um)?a(ba)?ba(ng)?']),
    encodeSubstitution('reduce',['(pina|(m|n)apa|(m|n)aka)?((m|n|p)ag?)?(pa|ka|i)?b(in|um)?a(ba)?was(ang?)?']),
    encodeSubstitution('regular',['regulate']),
    encodeSubstitution('relate',['relat(ed|es|ions|ionships?)']),
    encodeSubstitution('remove',['remov(al|es|ed|ing)']),
    encodeSubstitution('remove',['(pa(ng|m))?((n|m|p)ag?)?(ka|kaka)?t(um|in)?a(ta)?nggal(ing?)?']),
    encodeSubstitution('remove',['(pa(ng|m))?((n|m|p)ag?)?(ka|kaka)?a?alis(ing?)?']),
    encodeSubstitution('remove',['((b|m|p|n)aka?)?awa']),
    encodeSubstitution('remove',['(pa(ng|m))?((m|n)a|pina)?(pa)?(wa)?wala(ing?)?']),
    encodeSubstitution('replace',['replac(es|ed|ing)']),
    encodeSubstitution('request',['response']),
    encodeSubstitution('rest',['((m|n|p|k)ag?)?(ka|kaka)?(si)?p(um|in)?a(pa)?hinga(hing?|ng?)?']),
    encodeSubstitution('rest',['((ka)?(n|p|m)(i|e)nd|d|dim)(i|e)gka']),
    encodeSubstitution('rest',['(be?)?le?ne?k']),
    encodeSubstitution('restore',['restor(es|ed|ing|ate|ations?)', 'replenish(es|ed|ing)']),
    encodeSubstitution('restrict',['restrictions', '(pina|(m|n)apa|(m|n)aka|maki)?((m|n|p)ag?)?(pa|ka|i|ini)?b(in|um)?a(ba)?wal(ang?)?']),
    encodeSubstitution('result',['result(a|s|ed|ing)', 'consequences?']),
    encodeSubstitution('result',['((n|m)aka(ka)?|pinaka|i|kina)?((n|m|p)ag?)?(pa(pa|ng?)|i|ka)?l(um)?a(la)?bas(ang?)?']),
    encodeSubstitution('result',['((n|m)aka(ka)?|pinaka|i)?((n|m|p)ag?)?(pa(pa|ng?)|i|ka)?d(um)?u(du)?lot']),
    encodeSubstitution('result',['(p|m|n)ag(re)?resulta(ng)?']),
    encodeSubstitution('result',['l(e|i)?(nem|m)?y(u|o)']),
    encodeSubstitution('safe',['safe(ly|ty|tiness|r)', 'sav(e|es|ed|ing)', '(pina|napa)?((n|m|p)a)?(ka(ka)?)?l(um|in)?i(li)?gtas(ing?)?']),
    encodeSubstitution('same',['similar(ity)?', 'tulad', 'lik(e|ely|elihood)']),
    encodeSubstitution('seek',['seek(s|ed|ing)']),
    encodeSubstitution('severe',['sever(ity|eness)', '(pina|napa|naka)?((m|n|p)ag?)?(pa|ka|i)?l(um)?a(la)?la(ng)?']),
    encodeSubstitution('severe',['(pina|napa|naka)?((m|n|p)ag?)?(pa|ka|i)?l(um)?u(lu)?bha(an|ng)?', 'adverse']),
    encodeSubstitution('should',['shouldn']),
    encodeSubstitution('show',['shown']),
    encodeSubstitution('sign',['sign(s|als?|ages?)', 'senya(s|les)', 'warn(s|ed|ings?)?', 'cues?', 'babala']),
    encodeSubstitution('sign',['(nad?|mad?|kad?|p?ed)?sipat(an)?', 'padsa', '(pala)?tanda(ang?)?', 'hudyat', 'bakas']),
    encodeSubstitution('sigurado',['(pina|(m|n)apa|(m|n)aka|maki)?((m|n|p)ag?)?(pa|ka|i|ini)?s(in|um)?i(si)?gurado(ng?)?', 'ensure']),
    encodeSubstitution('sila',['silang']),
    encodeSubstitution('sira',['((m|n|p|k)ag?)?(ka|kaka)?(si)?s(um|in)?i(si)?ra(ing?|ng?)?']),
    encodeSubstitution('situation',['situations', 'sitwasyon']),
    encodeSubstitution('sneeze',['sneez(es|ed|ing)']),
    encodeSubstitution('sneeze',['((p|m|n)ag|(n|m)aka)?b(um|in)?a(ba)?hing(ang?)?']),
    encodeSubstitution('sneeze',['((p|n)?(e|i)m)?bale?n']),
    encodeSubstitution('solution',['solutions?', 'solusi?yon']),
    encodeSubstitution('source',['(re)?source(s)?']),
    encodeSubstitution('spread',['spread(s|ed|ing)']),
    encodeSubstitution('spread',['((n|m)aka(ka)?|pina(ka)?|i)?((n|m|p)ag?)?(pa(pa|ng?)?|i|ka(ka)?)?k(um|in)?a(ka)?lat(ang?|ing?)?']),
    encodeSubstitution('spread',['((n|m)aka(ka)?|pina(ka)?|i)?((n|m|p)ag?)?(pa(pa|ng?)?|i|ka(ka)?)?h(um|in)?a(ha)?wa(ang?|hang?)?']),
    encodeSubstitution('spread',['((n|m)aka(ka)?|pina(ka)?|i)?((n|m|p)ag?)?(pa(pa|ng?)?|i|ka(ka)?)?p(um|in)?a(pa)?sa(ang?|hang?)?']),
    encodeSubstitution('stay',['staying']),
    encodeSubstitution('stiff',['stiffness', 'kapa(pa)negas', 'paninigas', 'kadtegas', 'kapedtegas']),
    encodeSubstitution('stomach',['ti?yan', 'bituka']),
    encodeSubstitution('stop',['stop(ped|ping|s)?']),
    encodeSubstitution('stop',['refrain(s|ed|ing)?']),
    encodeSubstitution('stop',['suppress(ants|ing|ed|ions?)?']),
    encodeSubstitution('stop',['inhibit(ing|ions?|ed|s)']),
    encodeSubstitution('stop',['((m|n|p)ag?)?(ka|kaka|pa|papa)?(t|p)(um|in)?i((t|p)i)?gil(ang?)?']),
    encodeSubstitution('stop',['((m|n|p)ag?)?(ka|kaka|pa|papa)?(h)(um|in)?i(hi)?nto(ng)?']),
    encodeSubstitution('strain',['strains']),
    encodeSubstitution('suot',['(pina|(m|n)apa|(m|n)aka)?((m|n|p)ag?)?(pa|ka|i)?s(in|um)?u(su)?ot(ang?|ing?)?']),
    encodeSubstitution('supplement',['supplements']),
    encodeSubstitution('support',['supporting']),
    encodeSubstitution('sustansya',['masu(su)?stansya(ng)?']),
    encodeSubstitution('sweet',['sweeten(er|ers|ing)', 'syrups?', 'cand(y|ies)']),
    encodeSubstitution('sweet',['matatamis', 'kendi', 'mamis(en)?']),
    encodeSubstitution('symptom',['symptoms', 'sintomas']),
    encodeSubstitution('tablet',['tablet(s|as)']),
    encodeSubstitution('take',['((n|m)aka(ka)?|pina(ka)?|i)?((n|m|p)ag?)?(pa(pa|ng?)?|i|ka(ka)?)?t(um|in)?a(ta)?ke', 'tak(en|es|ing)', 'took']),
    encodeSubstitution('talk',['talk(s|ed|ing)', '(pina|(m|n)apa|(m|n)aka|(p|m)aki)?((m|n|p)ag?)?(pa|ka|i|ini)?s(in|um)?a(sa)?bi(ng?|hing?)?']),
    encodeSubstitution('tayo',['tayong']),
    encodeSubstitution('term',['terms']),
    encodeSubstitution('thing',['things']),
    encodeSubstitution('throat',['throats', 'lalamunan']),
    encodeSubstitution('throat',['tid(i|e)k', 'bak(i|e)lngan']),
    encodeSubstitution('tip',['tips']),
    encodeSubstitution('tip',['reminders?', 'precautions?']),
    encodeSubstitution('tip',['((m|n|p)ag?)?(pa|i)?p(in)?a(pa)?y(o|u)(h(a|i)n)?', 'paalala', 'isaalang(alang)?']),
    encodeSubstitution('touch',['touch(es|ed|ing)']),
    encodeSubstitution('treat',['treat(s|ed|ing|ments?)', 'alleviat(e|es|ed|ing)', 'cure', 'interv(ene|ing)']),
    encodeSubstitution('treat',['relief', 'reliev(e|es|ed|ers?|ing)', 'remed(yo?|ies)']),
    encodeSubstitution('treat',['(pina|napa)?((n|m)ag?|i)?l(um)?a(la)?kas']),
    encodeSubstitution('treat',['((n|m)a(p|k)a(ka)?|pinaka|i|(n|m)ag)?((n|m|p)ag?)?(pa(pa|ng?)|i|ka)?g(um|in)?a(ga)?m(u|o)t((a|i)ng?)?']),
    encodeSubstitution('treat',['((n|m)a(p|k)a(ka)?|i|(n|m)ag)?((n|m|p)ag?)?(pa(pa|ng?)|i|ka)?l(um)?u(lu)?nas((a|i)ng?)?']),
    encodeSubstitution('treat',['((n|m)a(p|k)a(ka)?|i|(n|m)ag)?((n|m|p)ag?)?(pa(pa|ng?)|i|ka)?(g(um)?a|pa)(ga)?ling(ing?)?']),
    encodeSubstitution('treat',['((n|m|p)aka|peng|(n|k)a)gam(o|u)t(an)?', 'gam(o|u)t(i|an)']),
    encodeSubstitution('treat',['recover(y|ed|s|ing)?', 'sooth(es?|ing)']),
    encodeSubstitution('try',['tr(ied|ying|ies)']),
    encodeSubstitution('tugon',['matutugunan']),
    encodeSubstitution('tukoy',['matutukoy']),
    encodeSubstitution('tunaw',['(pina|(m|n)apa|(m|n)aka|maki)?((m|n|p)ag?)?(pa|ka|i|ini)?t(in|um)?u(tu)?naw']),
    encodeSubstitution('turing',['itinuturing']),
    encodeSubstitution('turo',['magturo']),
    encodeSubstitution('use',['use(s|d|ful)', 'using', 'utiliz(e|ed|es|ation|ing)']),
    encodeSubstitution('use',['((m|n|p)ag?|pina)?(pa|papa|ka|kaka)?g(um|in)?a(ga)?mit((i|a)ng?)?']),
    encodeSubstitution('use',['penggam(e|i)ten', 'gemamit', '((n|m|g)a)?usal']),
    encodeSubstitution('vaccine',['((m|n|p)ag?)?(pa|papa|ka|ka)?b(um|in)?a(ba)?kuna(ng|hing?|hang?)?']),
    encodeSubstitution('vaccine',['vaccin(e|es|ed|ations?)']),
    encodeSubstitution('vaccine',['pam?bak(o|u)na', '(mapa|pa)d?t(i|e)?b(i|e)?k', '(i|e)?mbak(o|u)na', 'mapabak(o|u)na']),
    encodeSubstitution('virus',['viruses', 'viral']),
    encodeSubstitution('vomit',['vomit(s|ted|ing)', '((n|m|p)ag?)?(ka|kaka)?s(um|in)?u(su)?ka(ng|h(i|a)ng?)?']),
    encodeSubstitution('vomit',['((b|n|p|m)(an?g|aka))?(o|u)ta']),
    encodeSubstitution('water',['liquids?', 'likido', 'tubig', 'fluids?']),
    encodeSubstitution('weak',['(pina|napa|naka)?((m|n|p)ag?)?(pa|ka|i)?h(um)?i(hi)?na(ng)?']),
    encodeSubstitution('weak',['weak(en|ing)']),
    encodeSubstitution('weak',['((m|n|g|k)a)?l(o|u)bay(an)?']),
    encodeSubstitution('what',['(ano|ali)(ng)?', '(e|i)?ng(e|i)n']),
    encodeSubstitution('when',['k(e|ai)lan']),
    encodeSubstitution('when',['kanu']),
    encodeSubstitution('where',['(na)?saa?ng?']),
    encodeSubstitution('where',['(i|e)nda(u|o|w)']),
    encodeSubstitution('who',['who(m|se)', 'sino(ng)?', 'kanino(ng)?', 'ten', 'ta(i|y)n']),
    encodeSubstitution('why',['(ba)?kit']),
    encodeSubstitution('why',['((e|i)n)?d(o|u)k(i|e)n']),
    encodeSubstitution('work',['work(s|ed|ing)', 'operat(e|es|ed|ions?|ing)']),
    encodeSubstitution('work',['((n|m|p|b)(i|e)ng|(g|m|k|n)ang)?(ga)?galbek(an)?']),
    encodeSubstitution('work',['((n|m)ag?)?(g(um)?|p)a(ga)?na(ng)?', 'gana']),
    encodeSubstitution('work',['(pina|napa|naka)?((m|n|p)ag?)?(pa|ka|i)?g(um)?a(ga)?na(ng|hing?)?']),     
]