export let COMMON_MISPELLED_WORDS = [
    "abdominal",
    "acetaminophen",
    "alaxan",
    "allergy",
    "analgesic",
    "antidiarrheal",
    "antihistamine",
    "antimotility",
    "antitussives",
    // "aspirin",
    "benadryl",
    "biogesic",
    "bismuth",
    "branded",
    "cetirizine",
    "decongestant",
    "dextromethorphan",
    "diarrhea",
    "digestive",
    "direction",
    "disinfect",
    "different",
    "distance",
    // "electrolyte",
    // "embalangan",
    "expectorant",
    "generic",
    "guaifenesin",
    "headache",
    "ibuprofen",
    // "immune",
    "imodium",
    "infection",
    "influenza",
    // "kamahal",
    // "kapanegas",
    // "kasambot",
    // "lalamunan",
    "loperamide",
    "lozenges",
    // "medicol",
    // "mortin",
    "naproxen",
    // "panginginig",
    "paracetamol",
    "parasite",
    "petroleum",
    // "physical",
    // "prevent",
    // "probiotics",
    "pseudoephedrine",
    "rehydration",
    "robitussin",
    "senyales",
    "stiffness",
    "subsalicylate",
    "sudafed",
    "symptoms",
    "suppressants",
    // "sweetener",
    // "trigger",
    "vaccine",

]
